---

## 🔄 Dual-Write: Delta Lake + Any Database via `dlt`

LakeLogic natively features **`secondary_targets`** — enabling your Gold tables to write to Delta Lake (primary) and simultaneously fan out to PostgreSQL, Snowflake, BigQuery, or any of dlt's [30+ destinations](https://dlthub.com/docs/dlt-ecosystem/destinations/).

You can securely centralize database connection credentials within your system registry, keeping your individual data contracts clean and environment-agnostic. Any configuration prefixed with `dlt_` is dynamically passed to the destination:

```yaml
# 1. Centralize credentials in _domain.yaml or _system.yaml
materialization:
  _all:
    dlt_host: "${PG_HOST}"
    dlt_port: 5432
    dlt_username: "admin"
    dlt_password: "${PG_PASS}"
```

```yaml
# 2. Gold contract with dual materialization (inherits credentials)
materialization:
  strategy: merge
  target_path: data/gold_weather_summary
  format: delta                            # Primary: local Delta Lake

  secondary_targets:                       # Also fan out to:
    - format: dlt
      dlt_destination: postgres            # Maps to dlt's 'destination' parameter
      dlt_database: analytics_db           # Maps to dlt's 'database' parameter natively!
      dlt_dataset_name: analytics          # Maps to dlt's 'dataset_name' schema
      table_name: weather_summary
```

| dlt Destination | Install Command | Use Case |
|---|---|---|
| PostgreSQL | `%pip install dlt[postgres]` | Operational analytics |
| Snowflake | `%pip install dlt[snowflake]` | Cloud data warehouse |
| BigQuery | `%pip install dlt[bigquery]` | GCP analytics |
| Databricks | `%pip install dlt[databricks]` | Lakehouse |
| MotherDuck | `%pip install dlt[motherduck]` | Serverless DuckDB |
| Azure SQL | `%pip install dlt[mssql]` | Azure analytics |
| Redshift | `%pip install dlt[redshift]` | AWS warehouse |

> **Architecture:** dlt handles ingestion (REST API → Bronze) **and** dual-write (Gold → Delta + any DB). LakeLogic handles transforms, quality, lineage, and deduplication — all from a single YAML contract.

## 📦 Step 1 — Install Dependencies

We only need four packages:
- **`lakelogic`** — the contract-driven data mesh engine
- **`dlt`** — declarative REST API extraction
- **`prefect`** — workflow orchestration
- **`duckdb`** — in-process SQL engine for querying Delta tables

In [9]:
import os
import subprocess
import sys

# ── Install lakelogic & dependencies ──────────────────────────────────
# Update the path below to match your local lakelogic checkout.
# On Colab (or if the path doesn't exist), falls back to PyPI.
_LAKELOGIC_LOCAL = r"C:\_Personal\_SaaS\lakelogic"

if os.path.isdir(_LAKELOGIC_LOCAL):
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-e", f"{_LAKELOGIC_LOCAL}[dlt,duckdb]", "prefect", "-q"]
    )
    print(f"✅ Installed lakelogic (editable) with [dlt,duckdb] from {_LAKELOGIC_LOCAL}")
else:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "lakelogic[dlt,duckdb]", "prefect", "-q"])
    print("✅ Installed lakelogic[dlt,duckdb] from PyPI")

✅ Installed lakelogic (editable) from C:\_Personal\_SaaS\lakelogic

## ⚙️ Step 2 — Imports & Configuration

We import LakeLogic's registry and pipeline runner, set up Prefect, and create **interactive widgets** so you can change the target city coordinates without editing code.

> 💡 These widgets work like Databricks `dbutils.widgets` — change the values and re-run!

In [2]:
import os
import logging
import duckdb
import ipywidgets as widgets
from IPython.display import display

from prefect import flow, task
from lakelogic.core.registry import DomainRegistry
from lakelogic.pipeline.runner import LakehousePipeline

# ── Suppress noisy framework logs ──────────────────────────────────────
logging.getLogger("dlt").setLevel(logging.ERROR)
os.environ["PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW"] = "ignore"

# ── Parameterized Widgets ──────────────────────────────────────────────
lat_widget = widgets.FloatText(value=40.71, description="Latitude:", style={"description_width": "initial"})
lon_widget = widgets.FloatText(value=-74.01, description="Longitude:", style={"description_width": "initial"})

print("🌍 Set your target coordinates (default: New York City)")
display(lat_widget, lon_widget)

🌍 Set your target coordinates (default: New York City)

FloatText(value=40.71, description='Latitude:', style=DescriptionStyle(description_width='initial'))

FloatText(value=-74.01, description='Longitude:', style=DescriptionStyle(description_width='initial'))

### ⚙️ Execution Engine

In [ ]:
# Select execution engine (Colab comes with PySpark pre-installed)
ENGINE = "duckdb" # 'polars' , 'spark'

## 🌦️ Step 3 — Weather API Contracts (Bronze → Silver → Gold)

We define three YAML contracts for the [Open-Meteo API](https://open-meteo.com/) — one per medallion layer.

Each contract is a **declarative specification**:
- **Bronze** — raw ingestion via `dlt` ([Ingestion Docs](https://lakelogic.github.io/LakeLogic/contracts/data_product_contracts/ingestion.html#load-mode-validation))
- **Silver** — deduplicated via `merge` on `_dlt_id` ([Materialization Docs](https://lakelogic.github.io/LakeLogic/contracts/data_product_contracts/materialization.html))
- **Gold** — analytics-ready with **downstream consumer** declarations

The Silver layer also adds a **derived column** (`temperature_f`) and a **quality rule** to catch impossible temperatures.

> No API key required! Open-Meteo is free for non-commercial use.

In [3]:
os.makedirs("07_dlt_prefect_pipeline/contracts/weather", exist_ok=True)

latitude = lat_widget.value
longitude = lon_widget.value

# ── Bronze: Raw ingestion from Open-Meteo ──────────────────────────────
with open("07_dlt_prefect_pipeline/contracts/weather/bronze.yaml", "w") as f:
    f.write(f"""version: "1.0"

info:
  title: weather_forecast
  table_name: bronze_weather
  target_layer: bronze

dataset: bronze_weather

source:
  type: dlt
  dlt:
    base_url: https://api.open-meteo.com/v1
    endpoints:
      - name: forecast
        path: forecast
        params:
          latitude: {latitude}
          longitude: {longitude}
          current_weather: "true"

materialization:
  target_path: 07_dlt_prefect_pipeline/data/bronze_weather
  format: delta

  # Dual-write: also materialize to a database via dlt
  secondary_targets:
    - format: dlt
      dlt_destination: duckdb
      dlt_dataset_name: analytics
      table_name: weather_summary
""")

# ── Silver: Deduplicated merge ─────────────────────────────────────────
with open("07_dlt_prefect_pipeline/contracts/weather/silver.yaml", "w") as f:
    f.write("""version: "1.0"

info:
  title: weather_forecast_cleaned
  table_name: silver_weather_cleaned
  target_layer: silver

dataset: silver_weather_cleaned
primary_key: [_dlt_id]

source:
  type: table
  path: 07_dlt_prefect_pipeline/data/bronze_weather

transformations:
  - derive:
      field: temperature_f
      sql: "current_weather__temperature * 9.0 / 5.0 + 32.0"

quality:
  row_rules:
    - name: valid_temperature
      sql: "current_weather__temperature BETWEEN -90 AND 60"
      severity: error
      description: "Temperature must be within physically plausible range"

materialization:
  strategy: merge
  target_path: 07_dlt_prefect_pipeline/data/silver_weather_cleaned
  format: delta

  # Dual-write: also materialize to a database via dlt
  secondary_targets:
    - format: dlt
      dlt_destination: duckdb
      dlt_dataset_name: analytics
      table_name: weather_summary
""")

# ── Gold: Analytics-ready ──────────────────────────────────────────────
with open("07_dlt_prefect_pipeline/contracts/weather/gold.yaml", "w") as f:
    f.write("""version: "1.0"

info:
  title: weather_forecast
  table_name: gold_weather_summary
  target_layer: gold

dataset: gold_weather_summary
primary_key: [_dlt_id]

source:
  type: table
  path: 07_dlt_prefect_pipeline/data/silver_weather_cleaned

downstream:
  - type: dashboard
    name: Weather Monitoring Dashboard
    platform: grafana
    owner: platform-team
    refresh: "every 15 minutes"

  - type: api
    name: Weather Alerts Service
    platform: internal
    owner: ops-team

materialization:
  strategy: merge

  target_path: 07_dlt_prefect_pipeline/data/gold_weather_summary
  format: delta

  # Dual-write: also materialize to a database via dlt
  secondary_targets:
    - format: dlt
      dlt_destination: duckdb
      dlt_credentials: "duckdb_test_db.duckdb"
      dlt_dataset_name: analytics
      table_name: weather_summary
""")

print("✅ Weather contracts written: bronze.yaml, silver.yaml, gold.yaml")

✅ Weather contracts written: bronze.yaml, silver.yaml, gold.yaml

## 🗺️ Step 4 — Domain Registry (Dependency Graph + Lineage)

The **Domain Registry** is the single source of truth for your data mesh. It declares:
- 📂 Which contracts belong to which layer
- 🔗 The `depends_on` graph (so Gold waits for Silver, Silver waits for Bronze)
- 📊 **Lineage** tracking — every row gets stamped with `_lakelogic_loaded_at`
- 📋 **Run logs** — each pipeline execution is recorded for auditability

LakeLogic automatically resolves the dependency graph into a topological execution order.

```
bronze_weather ──→ silver_weather ──→ gold_weather_summary
```

In [4]:
with open("07_dlt_prefect_pipeline/_registry.yaml", "w") as f:
    f.write("""
domain: marketplace
system: colab_demo

# ── 1. Telemetry & Observability ──────────────────────────────────────────
# Both Run Logs and Quarantine records are dual-written to an analytics DB
# via dlt! Here we use DuckDB to simulate Postgres/Snowflake/BigQuery.
metadata:
  run_log_table: pipeline_runs
  run_log_backend: dlt
  dlt_destination: duckdb
  dlt_credentials: "07_dlt_prefect_pipeline/data/observability.duckdb"
  dlt_dataset_name: system_logs

quarantine:
  enabled: true
  table: quarantine_records
  format: dlt
  dlt_destination: duckdb
  dlt_credentials: "07_dlt_prefect_pipeline/data/observability.duckdb"
  dlt_dataset_name: system_logs

lineage:
  enabled: true
  timestamp_column_name: _lakelogic_loaded_at

storage:
  external_location_root: "."

external_sources:
  - name: "Weather (open-meteo) API"
    type: api
    consumed_by:
      - "bronze_weather"

contracts:
  # -- Bronze (no dependencies - these are the entry points) --
  - entity: bronze_weather
    layer: bronze
    path: contracts/weather/bronze.yaml

  # -- Silver (depends on Bronze) --
  - entity: silver_weather_cleaned
    layer: silver
    depends_on: [bronze_weather]
    path: contracts/weather/silver.yaml

  # -- Gold (depends on Silver) --
  - entity: gold_weather_summary
    layer: gold
    depends_on: [silver_weather_cleaned]
    path: contracts/weather/gold.yaml

""")

# Load and resolve all contracts + paths
registry = DomainRegistry.from_yaml("07_dlt_prefect_pipeline/_registry.yaml", storage_mode="direct")

print(f"✅ Registry loaded: {len(registry.contracts)} contracts across {registry.domain}/{registry.system}")
print(f"   Lineage: {registry.lineage.get('enabled', False)}")

2026-04-30 07:34:13.141 | WARNING  | lakelogic.core.registry:from_yaml:480 - Environment 'dev' not defined in registry; skipping dynamic substitutions.

✅ Registry loaded: 3 contracts across marketplace/colab_demo
   Lineage: True

### 🔀 Dependency Graph (DAG)

LakeLogic can render the full contract dependency graph as an interactive visualization. This is the exact execution order the pipeline will follow:

In [5]:
from IPython.display import HTML

pipeline_viz = LakehousePipeline(registry=registry, engine=ENGINE)
display(HTML(pipeline_viz.visualize_dag(title="Data Mesh (Demo) - Operations Domain / 1 System")))

## 🎯 Step 5 — Run the Pipeline with Prefect

This is where the magic happens. We wrap `LakehousePipeline` inside a Prefect `@task` and `@flow`.

**What LakeLogic does automatically:**
1. Reads each contract YAML
2. Resolves the dependency graph (Bronze → Silver → Gold)
3. Calls `dlt` to fetch data from the REST APIs
4. Validates, deduplicates, and materializes into Delta tables
5. Stamps every row with lineage metadata (`_lakelogic_loaded_at`, `_lakelogic_run_id`)
6. Returns a `PipelineRunSummary` with row counts and status per contract

**Pipeline parameters:**
| Parameter | Value | Why |
|-----------|-------|-----|
| `retry_attempts` | `1` | Single attempt (no retries for this demo) |
| `parallel` | `False` | Sequential execution for clean logs |
| `retry_base_wait_seconds` | `5` | Base wait between retries |
| `reload_layers` | `""` | Empty = incremental (no truncation) |

In [6]:
@task
def run_lakehouse_pipeline():
    """Runs the full Bronze -> Silver -> Gold pipeline and returns the summary."""
    pipeline = LakehousePipeline(registry=registry, engine=ENGINE)

    summary = pipeline.run(
        target_layers="bronze,silver,gold",  # to run only bronze pipelines -> "bronze"
        retry_attempts=1,
        parallel=False,
        retry_base_wait_seconds=5,
        reload_layers="",  # "bronze,silver,gold" -> # to reload only bronze -> "bronze"
        run_log_mode="table",
    )
    return summary


@flow(name="Colab Data Mesh Flow")
def orchestration_flow():
    """Prefect flow that wraps the LakeLogic pipeline execution."""
    summary = run_lakehouse_pipeline()
    print("\n" + str(summary))
    return summary


# Execute
pipeline_results = orchestration_flow()

07:34:15.944 | INFO    | prefect - Starting temporary server on http://127.0.0.1:8117
See https://docs.prefect.io/v3/concepts/server#how-to-guides for more information on running a dedicated Prefect server.

07:34:22.014 | INFO    | Flow run 'gainful-tamarin' - Beginning flow run 'gainful-tamarin' for flow 'Colab Data Mesh Flow'

2026-04-30 07:34:22.050 | INFO     | lakelogic.pipeline.runner:run:1503 - Pipeline storage mode: direct

2026-04-30 07:34:22.051 | INFO     | lakelogic.pipeline.runner:run:1604 - ── Processing Layer: BRONZE (1 contracts) ──

2026-04-30 07:34:22.054 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2067 -   ─────────────────────────────────────────────────────────

2026-04-30 07:34:22.055 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2068 -   📄 [bronze] bronze_weather | Contract: weather_forecast v1.0

2026-04-30 07:34:22.276 | INFO     | lakelogic.core.processor:_run_dlt_source:4148 - Running dlt source for contract: weather_forecast

2026-04-30 07:34:23.049 | INFO     | lakelogic.adapters.dlt_adapter:_run_rest_api:219 - dlt: running REST API source from https://api.open-meteo.com/v1

2026-04-30 07:34:23.320 | INFO     | lakelogic.adapters.dlt_adapter:_run_rest_api:251 - Restored dlt extraction state from lakelogic run logs.

2026-04-30 07:34:23,594|[WARNING]|31020|880|dlt|client.py|detect_paginator:365|Fallback `paginator` used: `SinglePagePaginator at 15cb78ebb90`. Please provide paginator manually.

2026-04-30 07:34:23.815 | INFO     | lakelogic.adapters.dlt_adapter:_collect_parquet_files:380 - dlt: collected 1 parquet file(s), 1 rows, 23 columns

2026-04-30 07:34:23.817 | INFO     | lakelogic.core.processor:_run_dlt_source:4169 - dlt: loaded 1 rows, 23 columns into Polars

2026-04-30 07:34:23.920 | INFO     | lakelogic.core.processor:run:818 - Run complete [layer=bronze] | Source: 1 | Total: 1 | Good: 1 | Quarantine: 0 | Ratio: 0.00%

2026-04-30 07:34:24.024 | INFO     | lakelogic.core.materialization:materialize_dataframe:3502 - Cast 1 column(s) to match existing Delta table schema

2026-04-30 07:34:24.036 | INFO     | lakelogic.core.materialization:materialize_dataframe:3662 - Delta pre-write state: 20 rows in 07_dlt_prefect_pipeline\data\bronze_weather (appending 1 new rows)

2026-04-30 07:34:24.194 | INFO     | lakelogic.core.materialization:materialize_dataframe:3728 - Materialized 1 rows to Delta table: 07_dlt_prefect_pipeline\data\bronze_weather (strategy=append, mode=append)

2026-04-30 07:34:24.781 | INFO     | lakelogic.core.materialization:_run_secondary_targets:3175 - Secondary target [0]: weather_summary → duckdb (append, 1 rows)

2026-04-30 07:34:25.003 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table 07_dlt_prefect_pipeline/data/_run_logs

2026-04-30 07:34:25.005 | INFO     | lakelogic.core.run_log:write_run_log:1068 - 📡 [1/5] Observatory config resolved: False

2026-04-30 07:34:25.005 | INFO     | lakelogic.core.run_log:write_run_log:1162 - 📡 [SKIP] Observatory disabled or not configured: cfg=False, enabled=N/A

2026-04-30 07:34:25.005 | INFO     | lakelogic.pipeline.runner:run:1604 - ── Processing Layer: SILVER (1 contracts) ──

2026-04-30 07:34:25.006 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2067 -   ─────────────────────────────────────────────────────────

2026-04-30 07:34:25.006 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2068 -   📄 [silver] silver_weather_cleaned | Contract: weather_forecast_cleaned v1.0

2026-04-30 07:34:25.024 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\07_dlt_prefect_pipeline\data\bronze_weather via duckdb

2026-04-30 07:34:25.260 | INFO     | lakelogic.core.processor:run:818 - Run complete [layer=silver] | Source: 21 | Total: 21 | Good: 21 | Quarantine: 0 | Ratio: 0.00%

2026-04-30 07:34:25.306 | INFO     | lakelogic.core.materialization:materialize_dataframe:3502 - Cast 1 column(s) to match existing Delta table schema

2026-04-30 07:34:25.465 | INFO     | lakelogic.core.materialization:materialize_dataframe:3631 - Materialized 21 rows to Delta table: 07_dlt_prefect_pipeline\data\silver_weather_cleaned (strategy=merge, pk=['_dlt_id'])

2026-04-30 07:34:25,590|[WARNING]|31020|880|dlt|extractors.py|_compute_tables:547|In resource: weather_summary, when merging arrow schema with dlt schema, several column hints were different. dlt schema hints were kept and arrow schema and data were unmodified. It is up to destination to coerce the differences when loading. Change log level to INFO for more details.

2026-04-30 07:34:25.945 | INFO     | lakelogic.core.materialization:_run_secondary_targets:3175 - Secondary target [0]: weather_summary → duckdb (merge, 21 rows)

2026-04-30 07:34:26.188 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table 07_dlt_prefect_pipeline/data/_run_logs

2026-04-30 07:34:26.189 | INFO     | lakelogic.core.run_log:write_run_log:1068 - 📡 [1/5] Observatory config resolved: False

2026-04-30 07:34:26.189 | INFO     | lakelogic.core.run_log:write_run_log:1162 - 📡 [SKIP] Observatory disabled or not configured: cfg=False, enabled=N/A

2026-04-30 07:34:26.191 | INFO     | lakelogic.pipeline.runner:run:1604 - ── Processing Layer: GOLD (1 contracts) ──

2026-04-30 07:34:26.191 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2067 -   ─────────────────────────────────────────────────────────

2026-04-30 07:34:26.192 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2068 -   📄 [gold] gold_weather_summary | Contract: weather_forecast v1.0

2026-04-30 07:34:26.213 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\07_dlt_prefect_pipeline\data\silver_weather_cleaned via duckdb

2026-04-30 07:34:26.308 | INFO     | lakelogic.core.processor:run:818 - Run complete [layer=gold] | Source: 21 | Total: 21 | Good: 21 | Quarantine: 0 | Ratio: 0.00%

2026-04-30 07:34:26.366 | INFO     | lakelogic.core.materialization:materialize_dataframe:3502 - Cast 1 column(s) to match existing Delta table schema

2026-04-30 07:34:26.557 | INFO     | lakelogic.core.materialization:materialize_dataframe:3631 - Materialized 21 rows to Delta table: 07_dlt_prefect_pipeline\data\gold_weather_summary (strategy=merge, pk=['_dlt_id'])

2026-04-30 07:34:26,688|[WARNING]|31020|880|dlt|extractors.py|_compute_tables:547|In resource: weather_summary, when merging arrow schema with dlt schema, several column hints were different. dlt schema hints were kept and arrow schema and data were unmodified. It is up to destination to coerce the differences when loading. Change log level to INFO for more details.

2026-04-30 07:34:27.092 | INFO     | lakelogic.core.materialization:_run_secondary_targets:3175 - Secondary target [0]: weather_summary → duckdb (merge, 21 rows)

2026-04-30 07:34:27.282 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table 07_dlt_prefect_pipeline/data/_run_logs

2026-04-30 07:34:27.284 | INFO     | lakelogic.core.run_log:write_run_log:1068 - 📡 [1/5] Observatory config resolved: False

2026-04-30 07:34:27.286 | INFO     | lakelogic.core.run_log:write_run_log:1162 - 📡 [SKIP] Observatory disabled or not configured: cfg=False, enabled=N/A

07:34:27.289 | INFO    | Task run 'run_lakehouse_pipeline-0a2' - Finished in state Completed()

================================================================================
 PIPELINE RUN SUMMARY
================================================================================
  Pipeline run    : 6af73256-f87f-4ebf-8674-5195971a723a
  Environment     : unknown
  Dry run         : False

  Table Name                             Layer    Status     Rows     Good/Qrtn
  ------------------------------------------------------------------------------
  bronze_weather                         bronze   success    1        1/0
  silver_weather_cleaned                 silver   success    21       21/0
  gold_weather_summary                   gold     success    21       21/0
================================================================================

07:34:28.050 | INFO    | Flow run 'gainful-tamarin' - Finished in state Completed()

---

## 🔄 Bonus: Write to Any Database with `dlt` Materialization

LakeLogic now supports **dlt as a materialization backend** — meaning your Gold tables can be written directly to PostgreSQL, Snowflake, BigQuery, Redshift, or any of dlt's [30+ destinations](https://dlthub.com/docs/dlt-ecosystem/destinations/).

The contract stays the same — just swap `format: delta` for `format: dlt`:

```yaml
# Example: Materialize Gold weather data to PostgreSQL
materialization:
  format: dlt
  dlt_destination: postgres
  dlt_credentials: "postgresql://user:pass@host:5432/analytics"
  dlt_dataset_name: gold
  strategy: merge
  primary_key: [_dlt_id]
```

| dlt Destination | Install Command | Use Case |
|---|---|---|
| PostgreSQL | `pip install dlt[postgres]` | Operational analytics |
| Snowflake | `pip install dlt[snowflake]` | Cloud data warehouse |
| BigQuery | `pip install dlt[bigquery]` | GCP analytics |
| Databricks | `pip install dlt[databricks]` | Lakehouse |
| MotherDuck | `pip install dlt[motherduck]` | Serverless DuckDB |
| Azure SQL | `pip install dlt[mssql]` | Azure analytics |
| Redshift | `pip install dlt[redshift]` | AWS warehouse |

> **The architecture:** dlt handles ingestion (REST API → Bronze) **and** materialization (Gold → any DB). LakeLogic handles everything in between — validation, transforms, quality, lineage, deduplication.

In [7]:
# The Gold contract already has secondary_targets configured.
# The pipeline run above wrote to BOTH Delta (primary) and DuckDB (secondary) via dlt.
# Verify by querying the dlt-managed DuckDB database:

import glob
import os

# Find the dlt-created DuckDB file
db_path = "duckdb_test_db.duckdb"
if os.path.exists(db_path):
    conn = duckdb.connect(db_path, read_only=True)
    tables = conn.execute(
        "SELECT table_schema, table_name FROM information_schema.tables WHERE table_schema='analytics'"
    ).fetchall()
    print(f"✅ Dual-write verified! dlt created: {db_path}")
    print(f"   Tables in analytics schema: {[t[1] for t in tables]}")
    row_count = conn.execute("SELECT COUNT(*) FROM analytics.weather_summary").fetchone()[0]
    print(f"   Rows in weather_summary: {row_count}")
    conn.close()
else:
    print("No secondary dlt database found yet.")
    print("Re-run the pipeline cell above to trigger dual-write.")
    print("To target PostgreSQL, change dlt_destination and add dlt_credentials.")

✅ Dual-write verified! dlt created: lakelogic_weather_summary_secondary.duckdb
   Tables in analytics schema: ['weather_summary', '_dlt_loads', '_dlt_pipeline_state', '_dlt_version']
   Rows in weather_summary: 21

## 📊 Step 6 — Query the Materialized Delta Tables

The pipeline just wrote Delta Lake tables to the `data/` directory. Let's query them with **DuckDB** to verify the results.

Notice the lineage columns that LakeLogic automatically injected:
- `_lakelogic_loaded_at` — when the row was processed
- `_lakelogic_run_id` — which pipeline run produced it
- `_lakelogic_created_by` — who ran the pipeline
- `_dlt_id` — deterministic row ID from `dlt` (used as the merge key)

In [8]:
conn = duckdb.connect()
conn.execute("INSTALL delta; LOAD delta;")

# Weather Gold
print("Weather Summary (Gold Layer)")
print("-" * 60)
df_weather = conn.execute("SELECT * FROM delta_scan('07_dlt_prefect_pipeline/data/gold_weather_summary') LIMIT 5").df()
display(df_weather)

# Run logs
print("run logs")
print("-" * 60)
df_run_logs = conn.execute("SELECT * FROM delta_scan('07_dlt_prefect_pipeline/data/_run_logs') LIMIT 5").df()
display(df_run_logs)

Weather Summary (Gold Layer)
------------------------------------------------------------

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,current_weather__time,current_weather__interval,current_weather__temperature,...,current_weather_units__is_day,current_weather_units__weathercode,_dlt_load_id,_dlt_id,temperature_f,_lakelogic_source,_lakelogic_loaded_at,_lakelogic_run_id,_lakelogic_created_at,_lakelogic_created_by
0,40.710335,-73.99308,0.114441,0,GMT,GMT,27.0,2026-04-30 07:30:00+01:00,900,9.1,...,,wmo code,1777530863.3839767,chhGdx9viN1XxA,48.38,C:\_Personal\_SaaS\lakelogic\examples\colab\07...,2026-04-30T06:34:26+00:00,9f290381-cb5b-476b-bc34-8e4c7e2a2928,2026-04-30T06:34:26+00:00,colli
1,40.710335,-73.99308,0.089049,0,GMT,GMT,27.0,2026-04-29 23:30:00+01:00,900,10.8,...,,wmo code,1777502166.7542346,1J69A+50AkLzBQ,51.44,C:\_Personal\_SaaS\lakelogic\examples\colab\07...,2026-04-30T06:34:26+00:00,9f290381-cb5b-476b-bc34-8e4c7e2a2928,2026-04-30T06:34:26+00:00,colli
2,40.710335,-73.99308,301.966429,0,GMT,GMT,27.0,2026-04-29 23:45:00+01:00,900,10.5,...,,wmo code,1777503010.8702285,GtRbqB2veRMo8g,50.90,C:\_Personal\_SaaS\lakelogic\examples\colab\07...,2026-04-30T06:34:26+00:00,9f290381-cb5b-476b-bc34-8e4c7e2a2928,2026-04-30T06:34:26+00:00,colli
3,40.710335,-73.99308,0.151157,0,GMT,GMT,27.0,2026-04-29 23:30:00+01:00,900,10.8,...,,wmo code,1777502030.7536218,a9DWuC3ra+7mMw,51.44,C:\_Personal\_SaaS\lakelogic\examples\colab\07...,2026-04-30T06:34:26+00:00,9f290381-cb5b-476b-bc34-8e4c7e2a2928,2026-04-30T06:34:26+00:00,colli
4,40.710335,-73.99308,0.101328,0,GMT,GMT,27.0,2026-04-29 23:45:00+01:00,900,10.5,...,,wmo code,1777503508.2529814,IMIVWXfLDWcMDg,50.90,C:\_Personal\_SaaS\lakelogic\examples\colab\07...,2026-04-30T06:34:26+00:00,9f290381-cb5b-476b-bc34-8e4c7e2a2928,2026-04-30T06:34:26+00:00,colli

run logs
------------------------------------------------------------

,pipeline_run_id,run_id,timestamp,start_time,end_time,run_duration_seconds,engine,contract,stage,dataset,...,counts_quarantined,quarantine_ratio,estimated_cost,cost_currency,cost_confidence,max_source_mtime,max_watermark_value,dlt_state_json,slo_json,report_json
0,6af73256-f87f-4ebf-8674-5195971a723a,9f290381-cb5b-476b-bc34-8e4c7e2a2928,2026-04-30T06:34:26+00:00,2026-04-30T06:34:26.246274+00:00,2026-04-30T06:34:26.337632+00:00,0.090420,duckdb,weather_forecast,default,gold_weather_summary,...,0,0.0,0.0,USD,none,1.777531e+09,None,None,"{""freshness"": {""seconds"": null, ""pass"": null, ...","{""run_id"": ""9f290381-cb5b-476b-bc34-8e4c7e2a29..."
1,6af73256-f87f-4ebf-8674-5195971a723a,ebdd359a-149b-4f00-a90f-a94ffa7da59a,2026-04-30T06:34:25+00:00,2026-04-30T06:34:25.123212+00:00,2026-04-30T06:34:25.283232+00:00,0.159508,duckdb,weather_forecast_cleaned,default,silver_weather_cleaned,...,0,0.0,0.0,USD,none,1.777531e+09,None,None,"{""freshness"": {""seconds"": null, ""pass"": null, ...","{""run_id"": ""ebdd359a-149b-4f00-a90f-a94ffa7da5..."
2,6af73256-f87f-4ebf-8674-5195971a723a,2833adea-2fa4-4d38-8e35-33cbcd0537fe,2026-04-30T06:34:23+00:00,2026-04-30T06:34:23.819710+00:00,2026-04-30T06:34:23.954847+00:00,0.134949,duckdb,weather_forecast,default,bronze_weather,...,0,0.0,0.0,USD,none,NaN,None,"{""_state_version"": 1, ""_state_engine_version"":...","{""freshness"": {""seconds"": null, ""pass"": null, ...","{""run_id"": ""2833adea-2fa4-4d38-8e35-33cbcd0537..."
3,5be0c1eb-40fe-4b7b-b288-823805208c0d,dfddbe7b-70b3-424b-901f-7f401e5dac0c,2026-04-30T06:33:43+00:00,2026-04-30T06:33:43.532063+00:00,2026-04-30T06:33:43.607723+00:00,0.075350,duckdb,weather_forecast,default,gold_weather_summary,...,0,0.0,0.0,USD,none,1.777531e+09,None,None,"{""freshness"": {""seconds"": null, ""pass"": null, ...","{""run_id"": ""dfddbe7b-70b3-424b-901f-7f401e5dac..."
4,5be0c1eb-40fe-4b7b-b288-823805208c0d,640b5632-f50d-4a31-8ce5-0af8a3015ca9,2026-04-30T06:33:43+00:00,2026-04-30T06:33:42.931084+00:00,2026-04-30T06:33:43.081445+00:00,0.151061,duckdb,weather_forecast_cleaned,default,silver_weather_cleaned,...,0,0.0,0.0,USD,none,1.777531e+09,None,None,"{""freshness"": {""seconds"": null, ""pass"": null, ...","{""run_id"": ""640b5632-f50d-4a31-8ce5-0af8a3015c..."

## 🔮 What's Next?

You just built a **production-grade data mesh pipeline** in a notebook. Here's how to take it further:

| Feature | How | Docs |
|---------|-----|------|
| **Add quality rules** | Add a `quality:` block to any contract YAML | [Quality Rules](https://lakelogic.github.io/LakeLogic/contracts/data_product_contracts/quality.html) |
| **Schema enforcement** | Add a `model:` block with typed field definitions | [Schema & Model](https://lakelogic.github.io/LakeLogic/contracts/schema_model.html#field-definition) |
| **Watermark strategies** | Use `watermark:` for time-based incremental loads | [Watermark Strategies](https://lakelogic.github.io/LakeLogic/contracts/data_product_contracts/watermark_strategies.html) |
| **Schedule with Prefect** | Add `schedule: cron("0 * * * *")` to your deployment | [Prefect Scheduling](https://docs.prefect.io/latest/concepts/schedules/) |
| **Switch to PostgreSQL** | Change `engine="duckdb"` → use `PostgreSQLConnector` | [LakeLogic Engines](https://lakelogic.github.io/LakeLogic/) |
| **Deploy to Databricks** | Point `storage_mode='uc'` and add a Unity Catalog | [Deployment Patterns](https://lakelogic.github.io/LakeLogic/) |

---

⭐ **Like this?** Star the repo → [github.com/LakeLogic/LakeLogic](https://github.com/LakeLogic/LakeLogic)

💬 **Questions?** Open a discussion or drop a comment on [r/dataengineering](https://www.reddit.com/r/dataengineering/)