⏱️ **Time required:** ~3 minutes | **Type:** Domain pipeline (run all cells)

# 🚗 RideFlow Marketplace — Domain Pipeline

**Domain Owner:** Marketplace Engineering  
**System:** rideflow  

This notebook represents the **Marketplace domain team's** autonomous pipeline. It generates synthetic ride-sharing data, processes it through the full Medallion architecture (Bronze → Silver → Gold), and publishes **Data Products** that other domains can consume.

| Published Data Product | Layer | Description |
| :-- | :-- | :-- |
| `silver_rideflow_trips` | Silver | Deduplicated, typed trip fact table |
| `silver_rideflow_driver_profiles` | Silver | Cleaned driver dimension |
| `silver_rideflow_rider_profiles` | Silver | Cleaned rider dimension |
| `gold_rideflow_trip_kpis` | Gold | Revenue, volume, distance KPIs |
| `gold_rideflow_rider_lifetime_value` | Gold | Rider LTV analysis |
| `gold_rideflow_surge_pricing_model` | Gold | Dynamic surge multipliers |

---
## Step 1 · Environment Setup

Install dependencies, detect runtime (Colab vs local), and configure paths.

In [1]:
import os
import subprocess
import sys

# ── Install lakelogic ─────────────────────────────────────────────────
# Update the path below to match your local lakelogic checkout.
# On Colab (or if the path doesn't exist), falls back to PyPI.
_LAKELOGIC_LOCAL = r"C:\_Personal\_SaaS\lakelogic"

if os.path.isdir(_LAKELOGIC_LOCAL):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", _LAKELOGIC_LOCAL, "-q"])
    print(f"\u2705 Installed lakelogic (editable) from {_LAKELOGIC_LOCAL}")
else:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "lakelogic", "-q"])
    print("\u2705 Installed lakelogic from PyPI")

✅ Installed lakelogic (editable) from C:\_Personal\_SaaS\lakelogic

In [2]:
import subprocess
import sys
import importlib
import os

# Install LakeLogic + dashboard dependencies if missing
for pkg in ["lakelogic", "panel", "hvplot", "pyparsing"]:
    if importlib.util.find_spec(pkg) is None:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", f"{pkg}[polars]" if pkg == "lakelogic" else pkg]
        )

# Detect environment
IN_COLAB = "google.colab" in sys.modules
print(f"Running in: {'Google Colab' if IN_COLAB else 'Local'}")


import _setup as s

Running in: Local
lakelogic v1.21.0 | Local | c:\_Personal\_SaaS\lakelogic\examples\colab

In [3]:
import panel as pn
import polars as pl
import lakelogic as ll
from pathlib import Path
from datetime import datetime, timezone

# Panel init — use colab comms if in Colab
if IN_COLAB:
    pn.extension("tabulator", comms="colab")
else:
    pn.extension("tabulator", design="bootstrap")

# Paths
DOMAIN_ROOT = Path("assets/domains_rideflow/marketplace/rideflow")
SYSTEM_YAML = str(DOMAIN_ROOT / "_system.yaml")
LAKEHOUSE = Path("./lakehouse")
LANDING_ROOT = LAKEHOUSE / "_data" / "landing_marketplace" / "rideflow"
os.environ["LAKELOGIC_OBSERVATORY_ENDPOINT"] = "http://127.0.0.1:3007/api/v1/operations/run-logs/ingest"
os.environ["LAKELOGIC_API_KEY"] = "llc_sk_9bdfa73e785acdaeb19ac23ee4f257b0"

# os.env['  endpoint: "${LAKELOGIC_OBSERVATORY_ENDPOINT}"  # e.g., "${LAKELOGIC_OBSERVATORY_ENDPOINT}"
#   api_key: "${LAKELOGIC_API_KEY}"   # e.g., "${LAKELOGIC_API_KEY}" for prod']

print(f"lakelogic v{ll.__version__}")
print(f"Lakehouse: {LAKEHOUSE.resolve()}")

lakelogic v1.21.0
Lakehouse: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse

---
## Step 2 · Load the Data Contract Registry

The `_system.yaml` registry is the single source of truth for this entire platform.
It declares every entity, its schema contract, lineage rules, materialization strategy, and cost model.

> Changing the `environment` parameter is all it takes to switch between local prototyping and Azure production.

In [4]:
from lakelogic.core.registry import DomainRegistry

ENV = "colab" if IN_COLAB else "local"
registry = DomainRegistry.from_yaml(SYSTEM_YAML, environment=ENV, storage_mode="direct")

print(f"Domain:  {registry.domain}")
print(f"System:  {registry.system}")
print(f"Env:     {ENV}")
print(f"\nContracts loaded: {len(registry.get_active_contracts())}")
for c in registry.get_active_contracts():
    print(f"  [{c.layer:6s}] {c.entity}")

2026-04-30 20:23:25.565 | INFO     | lakelogic.core.registry:from_yaml:404 - Domain config inherited from assets\domains_rideflow\marketplace\_domain.yaml
2026-04-30 20:23:25.566 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (_system.yaml): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.571 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: rider_profiles): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.576 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: rider_app_events): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.581 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: driver_profiles): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.585 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: driver_telemetry): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.589 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: trip_requests): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.596 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: trip_completed): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.600 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: trip_cancellations): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.606 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: silver_rideflow_driver_profiles): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.610 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: silver_rideflow_driver_telemetry): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.613 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: silver_rideflow_rider_profiles): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.620 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: silver_rideflow_trips): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.624 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: gold_rideflow_trip_kpis): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.627 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: gold_rideflow_driver_scorecard): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.632 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: gold_rideflow_rider_daily_metrics): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']
2026-04-30 20:23:25.635 | INFO     | lakelogic.core.registry:_validate_observatory_config:289 - ✅ Observatory (Contract: gold_rideflow_surge_pricing_model): config validated — endpoint=http://127.0.0.1:3007/api/v1/operations/run-logs/ingest, emit_on=['success', 'partial', 'failed'], environments=['dev', 'prod', 'staging', 'local']

Domain:  marketplace
System:  rideflow
Env:     local

Contracts loaded: 15
  [bronze] rider_profiles
  [bronze] rider_app_events
  [bronze] driver_profiles
  [bronze] driver_telemetry
  [bronze] trip_requests
  [bronze] trip_completed
  [bronze] trip_cancellations
  [silver] silver_rideflow_driver_profiles
  [silver] silver_rideflow_driver_telemetry
  [silver] silver_rideflow_rider_profiles
  [silver] silver_rideflow_trips
  [gold  ] gold_rideflow_trip_kpis
  [gold  ] gold_rideflow_driver_scorecard
  [gold  ] gold_rideflow_rider_daily_metrics
  [gold  ] gold_rideflow_surge_pricing_model

---
## Step 3 · Pipeline Lineage DAG

An interactive topological map of the RideFlow Data Mesh, automatically generated from the declarative `depends_on` rules in the Data Contracts.

In [5]:
from IPython.display import HTML
from lakelogic.pipeline.runner import LakehousePipeline

pipeline = LakehousePipeline(registry)
display(HTML(pipeline.visualize_dag(title="")))

2026-04-30 20:23:30.952 | DEBUG    | lakelogic.pipeline.runner:__init__:177 - Disabled DeletionVectors by default in Spark session for OSS compatibility.

---
## Step 4 · Generate Streaming Data

The `StreamingSimulator` generates **24 hours** of realistic ride-sharing data:
- **Dimension entities** (riders, drivers) with stable identity pools
- **Fact entities** (trip requests → completions → cancellations) following hour-of-day demand curves
- **Event entities** (telemetry, app events) proportional to active trips

All entities maintain **referential integrity** — every `rider_id` in a trip exists in the rider pool.

In [6]:
from lakelogic.core.streaming import StreamingSimulator
from datetime import timedelta

sim = StreamingSimulator.rideflow_marketplace(
    landing_root=str(LANDING_ROOT),
    window_minutes=60,
    start_time=datetime.now(timezone.utc) - timedelta(days=3),
    seed=42,
    initial_riders=200,
    initial_drivers=100,
)

print("🚀 Streaming simulator configured")
print(f"   Landing root: {LANDING_ROOT}")
print("   Window size:  60 minutes")
print("   Entities:     7 (2 dimensions, 3 facts, 2 events)")

🚀 Streaming simulator configured
   Landing root: lakehouse\_data\landing_marketplace\rideflow
   Window size:  60 minutes
   Entities:     7 (2 dimensions, 3 facts, 2 events)

In [7]:
# Generate 24 hours of simulated streaming data
NUM_WINDOWS = 24

total_rows = 0
windows = []
for window in sim.run(num_windows=NUM_WINDOWS, micro_batches=10, up_to=datetime.now(timezone.utc), resume=True):
    windows.append(window)
    total_rows += window.total_rows

print(f"\n{'=' * 60}")
if not windows:
    print("✅ No new windows generated. The simulator has caught up to the current time (up_to constraint reached).")
else:
    print(f"✅ Generated {total_rows:,} total rows across {len(windows)} windows")
    print(f"   Seed window:    {windows[0].total_rows:,} rows (initial pool)")
    print(f"   Avg per window: {total_rows // len(windows):,} rows")

# FK consistency check
fk = sim.validate_fk_consistency()
print("\n🔗 FK Consistency:")
print(f"   Riders:    {fk['total_riders']}")
print(f"   Drivers:   {fk['total_drivers']}")
print(f"   Healthy:   {'✅' if fk['fk_pools_healthy'] else '❌'}")

2026-04-30 20:23:30.988 | INFO     | lakelogic.core.streaming:_rebuild_state_from_landing:805 - No existing landing zone found -- starting fresh
2026-04-30 20:23:31.001 | INFO     | lakelogic.core.streaming:_seed_initial_pools:674 - 🌱 Seeded initial pools: 200 riders, 100 drivers
2026-04-30 20:23:31.050 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   0 | 2026-04-27 19:23 |   727 rows | rider_profiles=6 driver_profiles=2 trip_requests=92 trip_completed=55 trip_cancellations=9 driver_telemetry=412 rider_app_events=151 | 10 micro-batches/entity
2026-04-30 20:23:31.090 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   1 | 2026-04-27 20:23 |   639 rows | rider_profiles=6 driver_profiles=2 trip_requests=67 trip_completed=51 trip_cancellations=7 driver_telemetry=387 rider_app_events=119 | 10 micro-batches/entity
2026-04-30 20:23:31.129 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   2 | 2026-04-27 21:23 |   609 rows | rider_profiles=6 driver_profiles=2 trip_requests=58 trip_completed=45 trip_cancellations=8 driver_telemetry=358 rider_app_events=132 | 10 micro-batches/entity
2026-04-30 20:23:31.166 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   3 | 2026-04-27 22:23 |   515 rows | rider_profiles=6 driver_profiles=2 trip_requests=47 trip_completed=43 trip_cancellations=6 driver_telemetry=303 rider_app_events=108 | 10 micro-batches/entity
2026-04-30 20:23:31.206 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   4 | 2026-04-27 23:23 |   374 rows | rider_profiles=6 driver_profiles=2 trip_requests=41 trip_completed=32 trip_cancellations=5 driver_telemetry=208 rider_app_events=80 | 10 micro-batches/entity
2026-04-30 20:23:31.245 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   5 | 2026-04-28 00:23 |   369 rows | rider_profiles=6 driver_profiles=2 trip_requests=38 trip_completed=24 trip_cancellations=6 driver_telemetry=224 rider_app_events=69 | 10 micro-batches/entity
2026-04-30 20:23:31.279 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   6 | 2026-04-28 01:23 |   310 rows | rider_profiles=7 driver_profiles=2 trip_requests=26 trip_completed=28 trip_cancellations=5 driver_telemetry=171 rider_app_events=71 | 10 micro-batches/entity
2026-04-30 20:23:31.325 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   7 | 2026-04-28 02:23 |   324 rows | rider_profiles=7 driver_profiles=2 trip_requests=28 trip_completed=20 trip_cancellations=4 driver_telemetry=185 rider_app_events=78 | 10 micro-batches/entity
2026-04-30 20:23:31.360 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   8 | 2026-04-28 03:23 |   315 rows | rider_profiles=7 driver_profiles=2 trip_requests=28 trip_completed=21 trip_cancellations=5 driver_telemetry=192 rider_app_events=60 | 10 micro-batches/entity
2026-04-30 20:23:31.399 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window   9 | 2026-04-28 04:23 |   313 rows | rider_profiles=7 driver_profiles=2 trip_requests=30 trip_completed=21 trip_cancellations=5 driver_telemetry=182 rider_app_events=66 | 10 micro-batches/entity
2026-04-30 20:23:31.439 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  10 | 2026-04-28 05:23 |   317 rows | rider_profiles=7 driver_profiles=2 trip_requests=26 trip_completed=21 trip_cancellations=4 driver_telemetry=179 rider_app_events=78 | 10 micro-batches/entity
2026-04-30 20:23:31.486 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  11 | 2026-04-28 06:23 |   397 rows | rider_profiles=8 driver_profiles=2 trip_requests=38 trip_completed=26 trip_cancellations=5 driver_telemetry=232 rider_app_events=86 | 10 micro-batches/entity
2026-04-30 20:23:31.537 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  12 | 2026-04-28 07:23 |   545 rows | rider_profiles=8 driver_profiles=2 trip_requests=58 trip_completed=50 trip_cancellations=9 driver_telemetry=313 rider_app_events=105 | 10 micro-batches/entity
2026-04-30 20:23:31.599 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  13 | 2026-04-28 08:23 |   866 rows | rider_profiles=8 driver_profiles=2 trip_requests=104 trip_completed=66 trip_cancellations=10 driver_telemetry=490 rider_app_events=186 | 10 micro-batches/entity
2026-04-30 20:23:31.652 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  14 | 2026-04-28 09:23 |   685 rows | rider_profiles=8 driver_profiles=2 trip_requests=87 trip_completed=61 trip_cancellations=9 driver_telemetry=356 rider_app_events=162 | 10 micro-batches/entity
2026-04-30 20:23:31.709 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  15 | 2026-04-28 10:23 |   605 rows | rider_profiles=9 driver_profiles=2 trip_requests=64 trip_completed=44 trip_cancellations=9 driver_telemetry=347 rider_app_events=130 | 10 micro-batches/entity
2026-04-30 20:23:31.760 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  16 | 2026-04-28 11:23 |   645 rows | rider_profiles=9 driver_profiles=2 trip_requests=62 trip_completed=50 trip_cancellations=8 driver_telemetry=377 rider_app_events=137 | 10 micro-batches/entity
2026-04-30 20:23:31.814 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  17 | 2026-04-28 12:23 |   736 rows | rider_profiles=9 driver_profiles=2 trip_requests=67 trip_completed=55 trip_cancellations=9 driver_telemetry=432 rider_app_events=162 | 10 micro-batches/entity
2026-04-30 20:23:31.864 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  18 | 2026-04-28 13:23 |   630 rows | rider_profiles=9 driver_profiles=2 trip_requests=69 trip_completed=46 trip_cancellations=7 driver_telemetry=380 rider_app_events=117 | 10 micro-batches/entity
2026-04-30 20:23:31.915 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  19 | 2026-04-28 14:23 |   620 rows | rider_profiles=10 driver_profiles=2 trip_requests=59 trip_completed=41 trip_cancellations=9 driver_telemetry=358 rider_app_events=141 | 10 micro-batches/entity
2026-04-30 20:23:31.969 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  20 | 2026-04-28 15:23 |   656 rows | rider_profiles=10 driver_profiles=2 trip_requests=72 trip_completed=50 trip_cancellations=9 driver_telemetry=395 rider_app_events=118 | 10 micro-batches/entity
2026-04-30 20:23:32.025 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  21 | 2026-04-28 16:23 |   698 rows | rider_profiles=10 driver_profiles=2 trip_requests=83 trip_completed=54 trip_cancellations=9 driver_telemetry=391 rider_app_events=149 | 10 micro-batches/entity
2026-04-30 20:23:32.076 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  22 | 2026-04-28 17:23 |   913 rows | rider_profiles=11 driver_profiles=2 trip_requests=105 trip_completed=69 trip_cancellations=11 driver_telemetry=527 rider_app_events=188 | 10 micro-batches/entity
2026-04-30 20:23:32.131 | INFO     | lakelogic.core.streaming:run:771 - ⏱ Window  23 | 2026-04-28 18:23 |   886 rows | rider_profiles=11 driver_profiles=2 trip_requests=104 trip_completed=65 trip_cancellations=11 driver_telemetry=517 rider_app_events=176 | 10 micro-batches/entity

============================================================
✅ Generated 13,994 total rows across 25 windows
   Seed window:    300 rows (initial pool)
   Avg per window: 559 rows

🔗 FK Consistency:
   Riders:    391
   Drivers:   148
   Healthy:   ✅

In [8]:
# Verify partition structure
import glob

for entity in ["trip_requests", "trip_completed", "rider_profiles"]:
    files = glob.glob(str(LANDING_ROOT / entity / "**/*.csv"), recursive=True)
    print(f"  {entity}: {len(files)} partition files")
    if files:
        # Show first and last partition path
        files.sort()
        print(f"    First: {files[0].split(entity)[-1]}")
        print(f"    Last:  {files[-1].split(entity)[-1]}")

  trip_requests: 235 partition files
    First: \y_2026\m_04\d_27\h_19\batch_00_0d39d6.csv
    Last:  \y_2026\m_04\d_28\h_18\batch_09_daffdc.csv
  trip_completed: 219 partition files
    First: \y_2026\m_04\d_27\h_19\batch_00_9da49f.csv
    Last:  \y_2026\m_04\d_28\h_18\batch_09_664160.csv
  rider_profiles: 182 partition files
    First: \y_2026\m_04\d_27\h_19\batch_00_1ef399.csv
    Last:  \y_2026\m_04\d_28\h_18\batch_05_227693.csv

---
## Step 4.5 · Inject Deterministic Edge Cases (TC-001 to TC-008)

The StreamingSimulator above generated realistic, time-aware trip data with organic variance.
Now we surgically inject **exactly 800 edge-case rows** into the `trip_completed` landing directory.
These represent 8 specific failure modes that the pipeline's quarantine layer must catch:

| TC | Description | Rows | What the pipeline should catch |
| :-- | :-- | --: | :-- |
| TC-001 | Negative fare | 120 | Business logic: `fare_amount >= 0` |
| TC-002 | driver_id = rider_id | 80 | Self-service fraud detection |
| TC-003 | Dropoff before pickup | 150 | Temporal sanity: `dropoff_at > pickup_at` |
| TC-004 | Distance > 500km | 100 | Geospatial bounds check |
| TC-005 | SQL injection in notes | 150 | Security / input sanitization |
| TC-006 | Surge > 5.0x | 80 | Cap violation: `surge_multiplier <= 5.0` |
| TC-007 | Unknown city code | 60 | Referential integrity check |
| TC-008 | Duplicate trip_id | 60 | Idempotency / uniqueness constraint |

After the pipeline runs, we expect:
```
source_count = good_count + bad_count
"100% reconciliation. Every row accounted for."
```

In [9]:
# ── Deterministic Edge-Case Injection ────────────────────────────────────
# Injects exactly 800 mutated rows into the trip_completed landing zone
# so the pipeline quarantine layer can demonstrate 100% reconciliation.

import uuid
import random
from datetime import datetime, timedelta, timezone

random.seed(42)
NUM_EDGE_CASES = 800

CITY_PROFILES = {
    "LON": {"timezone": "Europe/London", "base_trips_per_hour": 500},
    "NYC": {"timezone": "US/Eastern", "base_trips_per_hour": 800},
    "BER": {"timezone": "Europe/Berlin", "base_trips_per_hour": 200},
    "PAR": {"timezone": "Europe/Paris", "base_trips_per_hour": 350},
    "TYO": {"timezone": "Asia/Tokyo", "base_trips_per_hour": 600},
    "SYD": {"timezone": "Australia/Sydney", "base_trips_per_hour": 150},
}

cities = list(CITY_PROFILES.keys())
base_time = datetime(2026, 4, 15, 8, 0, tzinfo=timezone.utc)

# Generate 800 base rows with valid structure
records = []
for i in range(NUM_EDGE_CASES):
    trip_id = str(uuid.uuid4())
    rider_id = f"R-{uuid.uuid4().hex[:8]}"
    driver_id = f"D-{uuid.uuid4().hex[:8]}"
    city = random.choice(cities)
    hr = random.choices(range(24), weights=[1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 4, 3, 1, 1, 1])[0]
    req_dt = base_time.replace(hour=hr, minute=random.randint(0, 59))
    pickup_dt = req_dt + timedelta(minutes=random.randint(1, 10))
    dropoff_dt = req_dt + timedelta(minutes=random.randint(15, 60))

    records.append(
        {
            "trip_id": trip_id,
            "rider_id": rider_id,
            "driver_id": driver_id,
            "trip_type": random.choice(["ride", "eats_delivery"]),
            "pickup_lat": str(round(random.uniform(51.4, 51.6), 6)),
            "pickup_lng": str(round(random.uniform(-0.2, 0.1), 6)),
            "dropoff_lat": str(round(random.uniform(51.4, 51.6), 6)),
            "dropoff_lng": str(round(random.uniform(-0.2, 0.1), 6)),
            "city_code": city,
            "requested_at": req_dt.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "pickup_at": pickup_dt.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "dropoff_at": dropoff_dt.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "distance_km": str(round(random.uniform(1, 25), 1)),
            "duration_minutes": str(random.randint(5, 45)),
            "fare_amount": str(round(random.uniform(5, 80), 2)),
            "surge_multiplier": str(round(random.uniform(1.0, 3.5), 2)),
            "tip_amount": str(round(random.uniform(0, 10), 2)),
            "payment_method": random.choice(["card", "apple_pay", "google_pay", "cash"]),
            "rider_rating": str(random.randint(1, 5)),
            "driver_rating": str(random.randint(1, 5)),
            "notes": "",
        }
    )

# ── Apply TC-001 to TC-008 mutations ──────────────────────────────────────
for i in range(0, 120):
    records[i]["fare_amount"] = "-15.50"  # TC-001: Negative fare
for i in range(120, 200):
    records[i]["driver_id"] = records[i]["rider_id"]  # TC-002: Self-service fraud
for i in range(200, 350):  # TC-003: Time travel
    records[i]["pickup_at"] = "2026-04-15T12:00:00Z"
    records[i]["dropoff_at"] = "2026-04-15T11:00:00Z"
for i in range(350, 450):
    records[i]["distance_km"] = "650.5"  # TC-004: Impossible trip
for i in range(450, 600):
    records[i]["notes"] = "DROP TABLE trips; SELECT * FROM users;"  # TC-005
for i in range(600, 680):
    records[i]["surge_multiplier"] = "5.8"  # TC-006: Cap violation
for i in range(680, 740):
    records[i]["city_code"] = "XYZ"  # TC-007: Unknown market
dup_id = records[0]["trip_id"]  # Reuse first trip's ID
for i in range(740, 800):
    records[i]["trip_id"] = dup_id  # TC-008: Duplicate ID

random.shuffle(records)
edge_df = pl.DataFrame(records)

# Write to the trip_completed landing directory as a separate partition file
edge_dir = LANDING_ROOT / "trip_completed" / "y_2026" / "m_04" / "d_15" / "h_99"
edge_dir.mkdir(parents=True, exist_ok=True)
edge_file = edge_dir / "edge_cases.csv"
edge_df.write_csv(str(edge_file))

print(f"\u2705 Injected {NUM_EDGE_CASES} deterministic edge cases into landing zone")
print(f"   File: {edge_file}")
print()
print("   TC-001  Negative fare:         120 rows")
print("   TC-002  driver_id=rider_id:      80 rows")
print("   TC-003  Dropoff before pickup:  150 rows")
print("   TC-004  Distance > 500km:       100 rows")
print("   TC-005  SQL injection in notes: 150 rows")
print("   TC-006  Surge > 5.0x:            80 rows")
print("   TC-007  Unknown city code:        60 rows")
print("   TC-008  Duplicate trip_id:        60 rows")
print(f"   {'=' * 45}")
print(f"   TOTAL edge cases:               {NUM_EDGE_CASES} rows")

✅ Injected 800 deterministic edge cases into landing zone
   File: lakehouse\_data\landing_marketplace\rideflow\trip_completed\y_2026\m_04\d_15\h_99\edge_cases.csv

   TC-001  Negative fare:         120 rows
   TC-002  driver_id=rider_id:      80 rows
   TC-003  Dropoff before pickup:  150 rows
   TC-004  Distance > 500km:       100 rows
   TC-005  SQL injection in notes: 150 rows
   TC-006  Surge > 5.0x:            80 rows
   TC-007  Unknown city code:        60 rows
   TC-008  Duplicate trip_id:        60 rows
   =============================================
   TOTAL edge cases:               800 rows

---
## Pipeline Config

- **retry_attempts**: Max retries if a dataset fails due to temporary network or storage glitches.
- **retry_base_wait_seconds**: Initial wait time before retrying. Automatically scales up (e.g., 5s, 10s, 20s) to avoid overwhelming the system.
- **parallel**: Processes independent datasets simultaneously across multiple CPU threads for much faster ingestion.
- **engine**: Defines the compute backend (`polars` for local speed, `spark` for distributed clusters).
- **reload_layers**: Forces a complete historical wipe and reload of specific layers (e.g., `"silver,gold"`).

In [10]:
retry_attempts = 1
parallel = False
retry_base_wait_seconds = 5
engine = "duckdb"
reload_layers = ""
enable_incremental_streaming = False

---
## Step 5 · Bronze Ingestion

Ingest the streaming landing data into Bronze Delta tables. Every row gets lineage columns (`_lakelogic_source`, `_lakelogic_processed_at`, `_lakelogic_run_id`) automatically injected.

In [11]:
from lakelogic.pipeline.runner import LakehousePipeline
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)

print("Starting Bronze Ingestion via LakeLogic Pipeline Driver...")
runner = LakehousePipeline(registry, engine=engine)

summary = runner.run(
    target_layers="bronze",
    reload_layers=reload_layers,
    dry_run=False,
    environment=ENV,
    retry_attempts=retry_attempts,
    retry_base_wait_seconds=retry_base_wait_seconds,
    parallel=False,
)
print(summary)

2026-04-30 20:23:32.314 | INFO     | lakelogic.pipeline.runner:run:1505 - Pipeline storage mode: direct
2026-04-30 20:23:32.317 | INFO     | lakelogic.pipeline.runner:run:1606 - ── Processing Layer: BRONZE (7 contracts) ──

Starting Bronze Ingestion via LakeLogic Pipeline Driver...

2026-04-30 20:23:32.320 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:32.321 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] rider_profiles | Contract: Bronze — RideFlow Rider Profiles v1.0.0
2026-04-30 20:23:32.384 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\rider_profiles via duckdb
2026-04-30 20:23:32.745 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:33.093 | WARNING  | lakelogic.core.masking_engine:apply:377 - PII fields detected without masking strategy: [name, email, phone, date_of_birth, home_address, city_code]. Set 'masking:' (nullify|hash|redact|partial|encrypt) in your contract to enable masking for these fields.
2026-04-30 20:23:33.093 | INFO     | lakelogic.core.masking_engine:apply:384 - No PII fields with explicit masking strategy — skipping masking.
2026-04-30 20:23:33.095 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 391 | Total: 391 | Good: 391 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:33.161 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 391 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_rider_profiles (strategy=append, mode=append)
2026-04-30 20:23:33.163 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:33.216 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for rider_profiles
2026-04-30 20:23:33.244 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:33.245 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:33.245 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:33.348 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Rider Profiles)
2026-04-30 20:23:33.422 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:33.422 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"0627e977-bc14-4003-a763-15c752847992","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:33.425 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:33.427 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] rider_app_events | Contract: Bronze — RideFlow Rider App Events v1.0.0
2026-04-30 20:23:33.442 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\rider_app_events via duckdb
2026-04-30 20:23:33.452 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:33.923 | WARNING  | lakelogic.core.masking_engine:apply:377 - PII fields detected without masking strategy: [event_name]. Set 'masking:' (nullify|hash|redact|partial|encrypt) in your contract to enable masking for these fields.
2026-04-30 20:23:33.924 | INFO     | lakelogic.core.masking_engine:apply:384 - No PII fields with explicit masking strategy — skipping masking.
2026-04-30 20:23:33.925 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 2869 | Total: 2869 | Good: 2869 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:33.979 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 2869 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_rider_app_events (strategy=append, mode=append)
2026-04-30 20:23:33.982 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:34.036 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for rider_app_events
2026-04-30 20:23:34.177 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:34.178 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:34.178 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:34.180 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Rider App Events)
2026-04-30 20:23:34.219 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:34.219 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"27ba8ceb-d033-458f-a94c-2dacb5ecb7b7","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:34.225 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:34.225 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] driver_profiles | Contract: Bronze — RideFlow Driver Profiles v1.0.0
2026-04-30 20:23:34.243 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\driver_profiles via duckdb
2026-04-30 20:23:34.261 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:34.368 | WARNING  | lakelogic.core.masking_engine:apply:377 - PII fields detected without masking strategy: [name, email, phone, date_of_birth, home_address, licence_number, city_code]. Set 'masking:' (nullify|hash|redact|partial|encrypt) in your contract to enable masking for these fields.
2026-04-30 20:23:34.369 | INFO     | lakelogic.core.masking_engine:apply:384 - No PII fields with explicit masking strategy — skipping masking.
2026-04-30 20:23:34.370 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 148 | Total: 148 | Good: 148 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:34.413 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 148 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_driver_profiles (strategy=append, mode=append)
2026-04-30 20:23:34.414 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:34.428 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for driver_profiles
2026-04-30 20:23:34.548 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:34.548 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:34.550 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:34.550 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Driver Profiles)
2026-04-30 20:23:34.599 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:34.600 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"a2874f68-902a-44c4-9d9e-af6d4deb08d6","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:34.603 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:34.604 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] driver_telemetry | Contract: Bronze — RideFlow Driver Telemetry v1.0.0
2026-04-30 20:23:34.620 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\driver_telemetry via duckdb
2026-04-30 20:23:34.642 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:34.946 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 7916 | Total: 7916 | Good: 7916 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:35.029 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 7916 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_driver_telemetry (strategy=append, mode=append)
2026-04-30 20:23:35.031 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:35.084 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for driver_telemetry
2026-04-30 20:23:35.226 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:35.227 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:35.227 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:35.228 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Driver Telemetry)
2026-04-30 20:23:35.273 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:35.274 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"81da7056-b310-4690-b060-48ec572c8300","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:35.279 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:35.280 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] trip_requests | Contract: Bronze — RideFlow Trip Requests v1.0.0
2026-04-30 20:23:35.294 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\trip_requests via duckdb
2026-04-30 20:23:35.330 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:35.575 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 1453 | Total: 1453 | Good: 1453 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:35.622 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 1453 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_trip_requests (strategy=append, mode=append)
2026-04-30 20:23:35.623 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:35.684 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for trip_requests
2026-04-30 20:23:35.829 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:35.829 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:35.829 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:35.830 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Trip Requests)
2026-04-30 20:23:35.903 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:35.904 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"f965829d-ebd5-4db3-b73a-b533b6628d1f","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:35.909 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:35.910 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] trip_completed | Contract: Bronze — RideFlow Trip Completed v1.0.0
2026-04-30 20:23:35.924 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\trip_completed via duckdb
2026-04-30 20:23:35.963 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:36.329 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 1838 | Total: 1838 | Good: 1838 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:36.383 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 1838 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_trip_completed (strategy=append, mode=append)
2026-04-30 20:23:36.384 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:36.430 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for trip_completed
2026-04-30 20:23:36.568 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:36.569 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:36.569 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:36.569 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Trip Completed)
2026-04-30 20:23:36.631 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:36.631 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"f93751dd-56c9-42a6-b781-04c4427859d2","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:36.636 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:36.636 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [bronze] trip_cancellations | Contract: Bronze — RideFlow Trip Cancellations v1.0.0
2026-04-30 20:23:36.650 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\_data\landing_marketplace\rideflow\trip_cancellations via duckdb
2026-04-30 20:23:36.698 | INFO     | lakelogic.core.processor:run_source:1441 - Initial load detected (no prior watermark) — scanning all partitions (set lookback_days to limit)
2026-04-30 20:23:36.870 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=bronze] | Source: 179 | Total: 179 | Good: 179 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:36.912 | INFO     | lakelogic.core.materialization:materialize_dataframe:3876 - Materialized 179 rows to Delta table: lakehouse\marketplace\bronze\bronze_rideflow_trip_cancellations (strategy=append, mode=append)
2026-04-30 20:23:36.912 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:36.951 | INFO     | lakelogic.pipeline.runner:_execute_post_ingestion_cleanup:1886 -   🧹 Post-ingestion: deleted landing files for trip_cancellations
2026-04-30 20:23:37.102 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:37.104 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:37.105 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:37.106 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Bronze — RideFlow Trip Cancellations)
2026-04-30 20:23:37.355 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:37.355 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"85eb195d-3e3f-4ecf-b147-3ecbe5626abd","quarantine_records":0,"status":"ingested"}

================================================================================
 PIPELINE RUN SUMMARY
================================================================================
  Pipeline run    : c6bcb99d-a869-41c8-a3b2-69098a1abaf0
  Environment     : local
  Dry run         : False

  Table Name                             Layer    Status     Rows     Good/Qrtn
  ------------------------------------------------------------------------------
  bronze_rideflow_rider_profiles         bronze   success    391      391/0
  bronze_rideflow_rider_app_events       bronze   success    2869     2869/0
  bronze_rideflow_driver_profiles        bronze   success    148      148/0
  bronze_rideflow_driver_telemetry       bronze   success    7916     7916/0
  bronze_rideflow_trip_requests          bronze   success    1453     1453/0
  bronze_rideflow_trip_completed         bronze   success    1838     1838/0
  bronze_rideflow_trip_cancellations     bronze   success    179      179/0
================================================================================

---
## Step 6 · Silver Processing

Silver layer: type casting, deduplication, and merge. Schema enforcement quarantines rows that don't match the contract — no silent data corruption.

In [12]:
print("Starting Silver Processing via LakeLogic Pipeline Driver...")

summary = runner.run(
    target_layers="silver",
    reload_layers=reload_layers,
    dry_run=False,
    environment=ENV,
    retry_attempts=retry_attempts,
    retry_base_wait_seconds=retry_base_wait_seconds,
    parallel=parallel,
)
print(summary)

2026-04-30 20:23:37.455 | INFO     | lakelogic.pipeline.runner:run:1505 - Pipeline storage mode: direct
2026-04-30 20:23:37.459 | INFO     | lakelogic.pipeline.runner:run:1606 - ── Processing Layer: SILVER (4 contracts) ──
2026-04-30 20:23:37.461 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:37.461 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [silver] silver_rideflow_driver_profiles | Contract: Silver — Rideflow Driver Profiles v1.0.0
2026-04-30 20:23:37.486 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\bronze\bronze_rideflow_driver_profiles via duckdb
2026-04-30 20:23:37.554 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.

Starting Silver Processing via LakeLogic Pipeline Driver...

2026-04-30 20:23:37.692 | WARNING  | lakelogic.core.masking_engine:apply:377 - PII fields detected without masking strategy: [name, email, phone, date_of_birth, home_address, licence_number, licence_plate, bank_account_last_four, city_code]. Set 'masking:' (nullify|hash|redact|partial|encrypt) in your contract to enable masking for these fields.
2026-04-30 20:23:37.692 | INFO     | lakelogic.core.masking_engine:apply:384 - No PII fields with explicit masking strategy — skipping masking.
2026-04-30 20:23:37.693 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=silver] | Source: 148 | Total: 148 | Good: 148 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:37.721 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 1 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
rating                              | double          | float
2026-04-30 20:23:37.745 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 148 rows to Delta table: lakehouse\marketplace\silver\silver_rideflow_driver_profiles (strategy=merge, pk=['driver_id'])
2026-04-30 20:23:37.746 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:37.892 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:37.893 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:37.894 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:37.894 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Silver — Rideflow Driver Profiles)
2026-04-30 20:23:37.942 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:37.943 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"bf88e9c5-608c-47ee-8075-d5afb88570dd","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:37.948 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:37.948 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [silver] silver_rideflow_rider_profiles | Contract: Silver — Rideflow Rider Profiles v1.0.0
2026-04-30 20:23:37.966 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\bronze\bronze_rideflow_rider_profiles via duckdb
2026-04-30 20:23:38.023 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.
2026-04-30 20:23:38.133 | INFO     | lakelogic.engines.duckdb:_run_dataset_rules:758 - Quality Check: rider_id_unique | Result: 0 (expected < 1.0) | Status: PASS
2026-04-30 20:23:38.161 | WARNING  | lakelogic.core.masking_engine:apply:377 - PII fields detected without masking strategy: [name, email, phone, date_of_birth, home_address, city_code]. Set 'masking:' (nullify|hash|redact|partial|encrypt) in your contract to enable masking for these fields.
2026-04-30 20:23:38.163 | INFO     | lakelogic.core.masking_engine:apply:384 - No PII fields with explicit masking strategy — skipping masking.
2026-04-30 20:23:38.164 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=silver] | Source: 391 | Total: 391 | Good: 391 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:38.209 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 391 rows to Delta table: lakehouse\marketplace\silver\silver_rideflow_rider_profiles (strategy=merge, pk=['rider_id'])
2026-04-30 20:23:38.210 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:38.362 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:38.364 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:38.364 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:38.364 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Silver — Rideflow Rider Profiles)
2026-04-30 20:23:38.425 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:38.427 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"fbc9722b-cdf2-4728-acb0-241fdb557275","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:38.431 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:38.431 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [silver] silver_rideflow_driver_telemetry | Contract: Silver — Rideflow Driver Telemetry v1.0.0
2026-04-30 20:23:38.454 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\bronze\bronze_rideflow_driver_telemetry via duckdb
2026-04-30 20:23:38.516 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.
2026-04-30 20:23:38.745 | INFO     | lakelogic.engines.duckdb:_run_dataset_rules:758 - Quality Check: telemetry_id_unique | Result: 0 (expected < 1.0) | Status: PASS
2026-04-30 20:23:38.815 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=silver] | Source: 7916 | Total: 7916 | Good: 7916 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:38.860 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 1 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
speed_kmh                           | double          | float
2026-04-30 20:23:38.890 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 7916 rows to Delta table: lakehouse\marketplace\silver\silver_rideflow_driver_telemetry (strategy=merge, pk=['telemetry_id'])
2026-04-30 20:23:38.892 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:39.042 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:39.042 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:39.042 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:39.043 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Silver — Rideflow Driver Telemetry)
2026-04-30 20:23:39.114 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:39.115 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"f6c8df74-5c30-46c7-9d95-9c1f058dddc2","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:39.119 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:39.120 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [silver] silver_rideflow_trips | Contract: Silver — Rideflow Trips v1.0.0
2026-04-30 20:23:39.137 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\bronze\bronze_rideflow_trip_completed via duckdb
2026-04-30 20:23:39.228 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.
2026-04-30 20:23:39.798 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=silver] | Source: 1838 | Total: 1838 | Good: 1718 | Quarantine: 120 | Ratio: 6.53%
2026-04-30 20:23:39.827 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 7 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
distance_km                         | double          | float
duration_minutes                    | int64           | int32
fare_amount                         | double          | float
surge_multiplier                    | double          | float
tip_amount                          | double          | float
rider_rating                        | double          | float
driver_rating                       | double          | float
2026-04-30 20:23:39.854 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 1718 rows to Delta table: lakehouse\marketplace\silver\silver_rideflow_trips (strategy=merge, pk=['trip_id'])
2026-04-30 20:23:39.867 | INFO     | lakelogic.core.quarantine:materialize_quarantine:911 - Wrote 120 quarantined rows to lakehouse\marketplace\_quarantine\silver_rideflow_trips (mode=append)
2026-04-30 20:23:40.015 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:40.016 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:40.016 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:40.017 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Silver — Rideflow Trips)
2026-04-30 20:23:40.085 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:40.087 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"b7ff35e7-d5ce-42fe-afb3-575b4cbd8b15","quarantine_records":0,"status":"ingested"}

================================================================================
 PIPELINE RUN SUMMARY
================================================================================
  Pipeline run    : c6bcb99d-a869-41c8-a3b2-69098a1abaf0
  Environment     : local
  Dry run         : False

  Table Name                             Layer    Status     Rows     Good/Qrtn
  ------------------------------------------------------------------------------
  silver_rideflow_driver_profiles        silver   success    148      148/0
  silver_rideflow_rider_profiles         silver   success    391      391/0
  silver_rideflow_driver_telemetry       silver   success    7916     7916/0
  silver_rideflow_trips                  silver   success    1718     1718/120
================================================================================

---
## Step 6.5 · Gold Processing (Business KPIs & ML Models)

Gold layer: where the business value is unlocked! Generates Trip KPIs, Rider LTV (Lifetime Value), and the AI-driven Surge Pricing data feeds.

In [13]:
# Generate surge inference landing data for the Surge Pricing ML Model contract
import polars as pl
import random
import uuid
from datetime import datetime, timezone, timedelta

SURGE_LANDING = LAKEHOUSE / "marketplace" / "surge_inference_landing"
SURGE_LANDING.mkdir(parents=True, exist_ok=True)

random.seed(42)
cities = ["LON", "MAN", "BIR", "LDS", "BRS", "EDI", "GLA"]
n = 200

surge_df = pl.DataFrame(
    {
        "inference_id": [str(uuid.uuid4()) for _ in range(n)],
        "model_version": [random.choice(["v2.1.0", "v2.2.0", "v2.3.0-beta"]) for _ in range(n)],
        "city_code": [random.choice(cities) for _ in range(n)],
        "demand_index": [round(random.uniform(0.5, 8.5), 2) for _ in range(n)],
        "surge_multiplier": [round(random.uniform(1.0, 4.2), 2) for _ in range(n)],
        "timestamp": [datetime.now(timezone.utc) - timedelta(minutes=random.randint(0, 1440)) for _ in range(n)],
    }
)

surge_df.write_parquet(SURGE_LANDING / "inferences.parquet")
print(f"✅ Generated {n} surge inference records → {SURGE_LANDING}")
surge_df.head(3)

✅ Generated 200 surge inference records → lakehouse\marketplace\surge_inference_landing

shape: (3, 6)
┌──────────────────┬───────────────┬───────────┬──────────────┬──────────────────┬─────────────────┐
│ inference_id     ┆ model_version ┆ city_code ┆ demand_index ┆ surge_multiplier ┆ timestamp       │
│ ---              ┆ ---           ┆ ---       ┆ ---          ┆ ---              ┆ ---             │
│ str              ┆ str           ┆ str       ┆ f64          ┆ f64              ┆ datetime[μs,    │
│                  ┆               ┆           ┆              ┆                  ┆ UTC]            │
╞══════════════════╪═══════════════╪═══════════╪══════════════╪══════════════════╪═════════════════╡
│ 907921d4-ba58-40 ┆ v2.3.0-beta   ┆ LON       ┆ 5.86         ┆ 2.42             ┆ 2026-04-30      │
│ ef-8f48-677566e1 ┆               ┆           ┆              ┆                  ┆ 02:38:40.129519 │
│ 2f29             ┆               ┆           ┆              ┆                  ┆ UTC             │
│ 42c655c9-5a77-46 ┆ v2.1.0        ┆ MAN       ┆ 3.01         ┆ 3.61             ┆ 2026-04-30      │
│ 73-85cd-9c50f1e0 ┆               ┆           ┆              ┆                  ┆ 15:53:40.129519 │
│ 33ca             ┆               ┆           ┆              ┆                  ┆ UTC             │
│ e8cd6736-db7e-49 ┆ v2.1.0        ┆ BRS       ┆ 2.62         ┆ 3.85             ┆ 2026-04-30      │
│ a1-badb-dfb1904d ┆               ┆           ┆              ┆                  ┆ 18:58:40.129519 │
│ 8734             ┆               ┆           ┆              ┆                  ┆ UTC             │
└──────────────────┴───────────────┴───────────┴──────────────┴──────────────────┴─────────────────┘

In [14]:
print("Starting Gold Processing via LakeLogic Pipeline Driver...\n")

summary = runner.run(
    target_layers="gold",
    reload_layers=reload_layers,
    dry_run=False,
    environment=ENV,
    retry_attempts=retry_attempts,
    retry_base_wait_seconds=retry_base_wait_seconds,
    parallel=parallel,
)
print(summary)

2026-04-30 20:23:40.153 | INFO     | lakelogic.pipeline.runner:run:1505 - Pipeline storage mode: direct
2026-04-30 20:23:40.157 | INFO     | lakelogic.pipeline.runner:run:1606 - ── Processing Layer: GOLD (4 contracts) ──
2026-04-30 20:23:40.158 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:40.158 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [gold] gold_rideflow_trip_kpis | Contract: Gold — Trip KPIs v1.0.0
2026-04-30 20:23:40.174 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\silver\silver_rideflow_trips via duckdb
2026-04-30 20:23:40.233 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.

Starting Gold Processing via LakeLogic Pipeline Driver...

2026-04-30 20:23:40.411 | INFO     | lakelogic.engines.duckdb:_register_links:172 - Registered link 'silver_trips_full' from lakehouse\marketplace\silver\silver_rideflow_trips (type=delta)
2026-04-30 20:23:40.826 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=gold] | Source: 1718 | Total: 19 | Good: 19 | Quarantine: 0 | Aggregated: 1699 | Ratio: 0.00%
2026-04-30 20:23:40.848 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 6 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
kpi_date                            | timestamp[us]   | date32[day]
total_trips                         | int64           | int32
total_revenue                       | double          | float
total_distance_km                   | double          | float
avg_fare                            | double          | float
avg_surge                           | double          | float
2026-04-30 20:23:40.866 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 19 rows to Delta table: lakehouse\marketplace\gold\gold_rideflow_trip_kpis (strategy=merge, pk=['kpi_date', 'city_code'])
2026-04-30 20:23:40.867 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:41.020 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:41.022 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:41.024 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:41.024 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Gold — Trip KPIs)
2026-04-30 20:23:41.068 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:41.068 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"8111ad7c-4bfa-4a7a-a20f-f1a766968670","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:41.074 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:41.075 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [gold] gold_rideflow_driver_scorecard | Contract: Gold — Driver Scorecard v1.0.0
2026-04-30 20:23:41.090 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\silver\silver_rideflow_trips via duckdb
2026-04-30 20:23:41.148 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.
2026-04-30 20:23:41.331 | INFO     | lakelogic.engines.duckdb:_register_links:172 - Registered link 'silver_trips_full' from lakehouse\marketplace\silver\silver_rideflow_trips (type=delta)
2026-04-30 20:23:41.738 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=gold] | Source: 1718 | Total: 822 | Good: 822 | Quarantine: 0 | Aggregated: 896 | Ratio: 0.00%
2026-04-30 20:23:41.762 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 5 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
total_trips                         | int64           | int32
total_earnings                      | double          | float
avg_driver_rating                   | double          | float
avg_distance_km                     | double          | float
avg_duration_minutes                | double          | float
2026-04-30 20:23:41.781 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 822 rows to Delta table: lakehouse\marketplace\gold\gold_rideflow_driver_scorecard (strategy=merge, pk=['driver_id'])
2026-04-30 20:23:41.783 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:41.932 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:41.934 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:41.934 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:41.935 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Gold — Driver Scorecard)
2026-04-30 20:23:41.979 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:41.979 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"f0c470d8-a58a-4086-a894-9c23117829d4","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:41.983 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:41.984 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [gold] gold_rideflow_rider_daily_metrics | Contract: Gold — Daily Rider Metrics v1.0.0
2026-04-30 20:23:41.998 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\silver\silver_rideflow_trips via duckdb
2026-04-30 20:23:42.064 | INFO     | lakelogic.core.processor:run_source:1815 - Incremental load: first run or target empty — loading all rows.
2026-04-30 20:23:42.229 | INFO     | lakelogic.engines.duckdb:_register_links:172 - Registered link 'silver_trips_full' from lakehouse\marketplace\silver\silver_rideflow_trips (type=delta)
2026-04-30 20:23:42.618 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=gold] | Source: 1718 | Total: 1135 | Good: 1135 | Quarantine: 0 | Aggregated: 583 | Ratio: 0.00%
2026-04-30 20:23:42.645 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 5 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
activity_date                       | timestamp[us]   | date32[day]
daily_trips                         | int64           | int32
daily_spend                         | double          | float
daily_tips                          | double          | float
avg_daily_rating                    | double          | float
2026-04-30 20:23:42.658 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 1135 rows to Delta table: lakehouse\marketplace\gold\gold_rideflow_rider_daily_metrics (strategy=merge, pk=['rider_id', 'activity_date'])
2026-04-30 20:23:42.660 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:42.795 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:42.796 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:42.796 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:42.796 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Gold — Daily Rider Metrics)
2026-04-30 20:23:42.842 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:42.843 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"db55f434-5380-466b-bdc1-843cbd03ed55","quarantine_records":0,"status":"ingested"}
2026-04-30 20:23:42.848 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2069 -   ─────────────────────────────────────────────────────────
2026-04-30 20:23:42.849 | INFO     | lakelogic.pipeline.runner:_process_single_contract:2070 -   📄 [gold] gold_rideflow_surge_pricing_model | Contract: Gold — Surge Pricing ML Model Log v1.0.0
2026-04-30 20:23:42.863 | INFO     | lakelogic.core.processor:run_source:1374 - Loading source: C:\_Personal\_SaaS\lakelogic\examples\colab\lakehouse\marketplace\surge_inference_landing via duckdb
2026-04-30 20:23:42.895 | INFO     | lakelogic.engines.duckdb:_run_dataset_rules:758 - Quality Check: inference_id_unique | Result: 0 (expected < 1.0) | Status: PASS
2026-04-30 20:23:42.911 | INFO     | lakelogic.core.processor:run:818 - Run complete [domain=marketplace, system=rideflow, layer=gold] | Source: 200 | Total: 200 | Good: 200 | Quarantine: 0 | Ratio: 0.00%
2026-04-30 20:23:42.933 | INFO     | lakelogic.core.materialization:materialize_dataframe:3686 -
Casting 2 column(s) to match contract types before Delta write (new table):
Column Name                         | From Type       | To Type
-----------------------------------------------------------------------
demand_index                        | double          | float
surge_multiplier                    | double          | float
2026-04-30 20:23:42.949 | INFO     | lakelogic.core.materialization:materialize_dataframe:3779 - Materialized 200 rows to Delta table: lakehouse\marketplace\gold\gold_rideflow_surge_pricing_model (strategy=merge, pk=['inference_id'])
2026-04-30 20:23:42.950 | INFO     | lakelogic.core.quarantine:materialize_quarantine:627 - Quarantine materialization skipped: 0 bad rows.
2026-04-30 20:23:43.087 | INFO     | lakelogic.core.run_log:_write_run_log_table:872 - Wrote run log to Delta table ./lakehouse/marketplace/_logs
2026-04-30 20:23:43.089 | INFO     | lakelogic.core.run_log:write_run_log:1113 - 📡 [1/5] Observatory config resolved: True
2026-04-30 20:23:43.089 | INFO     | lakelogic.core.run_log:write_run_log:1130 - 📡 [2/5] Filters: env=local in ['dev', 'prod', 'staging', 'local'] → True | status=success in ['success', 'partial', 'failed'] → True
2026-04-30 20:23:43.089 | INFO     | lakelogic.core.run_log:write_run_log:1190 - 📡 [3/5] Posting to http://127.0.0.1:3007/api/v1/operations/run-logs/ingest (contract=Gold — Surge Pricing ML Model Log)
2026-04-30 20:23:43.155 | INFO     | lakelogic.core.run_log:write_run_log:1194 - 📡 [4/5] Response: HTTP 200
2026-04-30 20:23:43.155 | INFO     | lakelogic.core.run_log:write_run_log:1196 - 📡 [5/5] ✅ Ingested: {"run_id":"e68de964-68c0-4b39-a9d5-0c0fe15dc1d6","quarantine_records":0,"status":"ingested"}

================================================================================
 PIPELINE RUN SUMMARY
================================================================================
  Pipeline run    : c6bcb99d-a869-41c8-a3b2-69098a1abaf0
  Environment     : local
  Dry run         : False

  Table Name                             Layer    Status     Rows     Good/Qrtn
  ------------------------------------------------------------------------------
  gold_rideflow_trip_kpis                gold     success    19       19/0
  gold_rideflow_driver_scorecard         gold     success    822      822/0
  gold_rideflow_rider_daily_metrics      gold     success    1135     1135/0
  gold_rideflow_surge_pricing_model      gold     success    200      200/0
================================================================================

---
## Step 7 · Quick Data Preview

Inspect the Silver trips table — the main fact table driving the dashboard.

In [15]:
trips_path = LAKEHOUSE / registry.domain / registry.silver_layer / "silver_rideflow_trips"

if trips_path.exists():
    try:
        trips_df = pl.read_delta(str(trips_path))
    except Exception:
        parquets = list(trips_path.rglob("*.parquet"))
        trips_df = pl.read_parquet(parquets[0]) if parquets else pl.DataFrame()

    print(f"Silver trips: {len(trips_df):,} rows, {len(trips_df.columns)} columns")
    print(f"\nColumns: {trips_df.columns}")
    print("\nSample (5 rows):")
    display(trips_df.head(5))

    # Quick stats
    if "fare_amount" in trips_df.columns:
        fare_col = trips_df["fare_amount"].cast(pl.Float64, strict=False)
        print(f"\n📊 Fare stats:  min=£{fare_col.min():.2f}  avg=£{fare_col.mean():.2f}  max=£{fare_col.max():.2f}")
    if "city_code" in trips_df.columns:
        print(f"🏙️ Cities: {trips_df['city_code'].unique().sort().to_list()}")
else:
    print("⚠️ Silver trips table not found — check the pipeline cells above.")

Silver trips: 1,718 rows, 26 columns

Columns: ['trip_id', 'rider_id', 'driver_id', 'trip_type', 'pickup_lat', 'pickup_lng', 'dropoff_lat', 'dropoff_lng', 'city_code', 'requested_at', 'pickup_at', 'dropoff_at', 'distance_km', 'duration_minutes', 'fare_amount', 'surge_multiplier', 'tip_amount', 'payment_method', 'rider_rating', 'driver_rating', 'notes', '_lakelogic_source', '_lakelogic_processed_at', '_lakelogic_run_id', '_lakelogic_created_at', '_lakelogic_created_by']

Sample (5 rows):

shape: (5, 26)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tri ┆ rid ┆ dri ┆ tri ┆ pic ┆ pic ┆ dro ┆ dro ┆ cit ┆ req ┆ pic ┆ dro ┆ dis ┆ dur ┆ far ┆ sur ┆ tip ┆ pay ┆ rid ┆ dri ┆ not ┆ _la ┆ _la ┆ _la ┆ _la ┆ _la │
│ p_i ┆ er_ ┆ ver ┆ p_t ┆ kup ┆ kup ┆ pof ┆ pof ┆ y_c ┆ ues ┆ kup ┆ pof ┆ tan ┆ ati ┆ e_a ┆ ge_ ┆ _am ┆ men ┆ er_ ┆ ver ┆ es  ┆ kel ┆ kel ┆ kel ┆ kel ┆ kel │
│ d   ┆ id  ┆ _id ┆ ype ┆ _la ┆ _ln ┆ f_l ┆ f_l ┆ ode ┆ ted ┆ _at ┆ f_a ┆ ce_ ┆ on_ ┆ mou ┆ mul ┆ oun ┆ t_m ┆ rat ┆ _ra ┆ --- ┆ ogi ┆ ogi ┆ ogi ┆ ogi ┆ ogi │
│ --- ┆ --- ┆ --- ┆ --- ┆ t   ┆ g   ┆ at  ┆ ng  ┆ --- ┆ _at ┆ --- ┆ t   ┆ km  ┆ min ┆ nt  ┆ tip ┆ t   ┆ eth ┆ ing ┆ tin ┆ str ┆ c_s ┆ c_p ┆ c_r ┆ c_c ┆ c_c │
│ str ┆ str ┆ str ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ str ┆ --- ┆ dat ┆ --- ┆ --- ┆ ute ┆ --- ┆ lie ┆ --- ┆ od  ┆ --- ┆ g   ┆     ┆ our ┆ roc ┆ un_ ┆ rea ┆ rea │
│     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆ str ┆     ┆ dat ┆ eti ┆ dat ┆ f32 ┆ s   ┆ f32 ┆ r   ┆ f32 ┆ --- ┆ f32 ┆ --- ┆     ┆ ce  ┆ ess ┆ id  ┆ ted ┆ ted │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆ me[ ┆ eti ┆     ┆ --- ┆     ┆ --- ┆     ┆ str ┆     ┆ f32 ┆     ┆ --- ┆ ed_ ┆ --- ┆ _at ┆ _by │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆ μs] ┆ me[ ┆     ┆ i32 ┆     ┆ f32 ┆     ┆     ┆     ┆     ┆     ┆ str ┆ at  ┆ str ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 181 ┆ R-8 ┆ D-1 ┆ eat ┆ 51. ┆ 0.0 ┆ 51. ┆ -0. ┆ XYZ ┆ 202 ┆ 202 ┆ 202 ┆ 9.4 ┆ 19  ┆ 11. ┆ 3.4 ┆ 1.1 ┆ cas ┆ 4.0 ┆ 4.0 ┆     ┆ C:\ ┆ 202 ┆ 19b ┆ 202 ┆ col │
│ 497 ┆ d31 ┆ cae ┆ s_d ┆ 552 ┆ 167 ┆ 433 ┆ 169 ┆     ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 91  ┆ 7   ┆ 2   ┆ h   ┆     ┆     ┆     ┆ _Pe ┆ 6-0 ┆ 397 ┆ 6-0 ┆ li  │
│ 62- ┆ 8ca ┆ 618 ┆ eli ┆ 5   ┆ 57  ┆ 948 ┆ 965 ┆     ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rso ┆ 4-3 ┆ 83- ┆ 4-3 ┆     │
│ cce ┆ e   ┆ 6   ┆ ver ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nal ┆ 0T1 ┆ a4f ┆ 0T1 ┆     │
│ a-4 ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 20: ┆ 21: ┆ 21: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \_S ┆ 9:2 ┆ 6-4 ┆ 9:2 ┆     │
│ 8cf ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 58: ┆ 05: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aaS ┆ 3:3 ┆ 3d1 ┆ 3:3 ┆     │
│ -8f ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \la ┆ 9+0 ┆ -af ┆ 9+0 ┆     │
│ 76- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kel ┆ 0:0 ┆ 4c- ┆ 0:0 ┆     │
│ da6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ogi ┆ 0   ┆ 628 ┆ 0   ┆     │
│ cb2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c\e ┆     ┆ f9d ┆     ┆     │
│ f36 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ xam ┆     ┆ 0c0 ┆     ┆     │
│ 4e6 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ ee4 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s\c ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b\l ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ake ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se\ ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mar ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ket ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce\ ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bro ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nze ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \br ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ onz ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e_r ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ide ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ flo ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ w_t ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ete ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     │
│ d81 ┆ R-9 ┆ D-0 ┆ eat ┆ 51. ┆ -0. ┆ 51. ┆ -0. ┆ XYZ ┆ 202 ┆ 202 ┆ 202 ┆ 15. ┆ 42  ┆ 48. ┆ 2.0 ┆ 3.9 ┆ app ┆ 3.0 ┆ 3.0 ┆     ┆ C:\ ┆ 202 ┆ 19b ┆ 202 ┆ col │
│ 95f ┆ 075 ┆ 19c ┆ s_d ┆ 432 ┆ 035 ┆ 550 ┆ 068 ┆     ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 8   ┆     ┆ 200 ┆ 9   ┆ 9   ┆ le_ ┆     ┆     ┆     ┆ _Pe ┆ 6-0 ┆ 397 ┆ 6-0 ┆ li  │
│ ff- ┆ b32 ┆ 393 ┆ eli ┆ 549 ┆ 967 ┆ 409 ┆ 297 ┆     ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆     ┆     ┆ 001 ┆     ┆     ┆ pay ┆     ┆     ┆     ┆ rso ┆ 4-3 ┆ 83- ┆ 4-3 ┆     │
│ e07 ┆ 4   ┆ 5   ┆ ver ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nal ┆ 0T1 ┆ a4f ┆ 0T1 ┆     │
│ a-4 ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆ 18: ┆ 18: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \_S ┆ 9:2 ┆ 6-4 ┆ 9:2 ┆     │
│ 490 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06: ┆ 09: ┆ 43: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aaS ┆ 3:3 ┆ 3d1 ┆ 3:3 ┆     │
│ -84 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \la ┆ 9+0 ┆ -af ┆ 9+0 ┆     │
│ 06- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kel ┆ 0:0 ┆ 4c- ┆ 0:0 ┆     │
│ 356 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ogi ┆ 0   ┆ 628 ┆ 0   ┆     │
│ 4ec ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c\e ┆     ┆ f9d ┆     ┆     │
│ cc0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ xam ┆     ┆ 0c0 ┆     ┆     │
│ b72 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ ee4 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s\c ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b\l ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ake ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se\ ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mar ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ket ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce\ ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bro ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nze ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \br ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ onz ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e_r ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ide ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ flo ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ w_t ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ete ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     │
│ 754 ┆ R-a ┆ D-7 ┆ eat ┆ 51. ┆ -0. ┆ 51. ┆ -0. ┆ LON ┆ 202 ┆ 202 ┆ 202 ┆ 18. ┆ 22  ┆ 75. ┆ 5.8 ┆ 2.9 ┆ goo ┆ 1.0 ┆ 5.0 ┆     ┆ C:\ ┆ 202 ┆ 19b ┆ 202 ┆ col │
│ 03d ┆ 31b ┆ f57 ┆ s_d ┆ 534 ┆ 063 ┆ 464 ┆ 146 ┆     ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 299 ┆     ┆ 860 ┆     ┆ 7   ┆ gle ┆     ┆     ┆     ┆ _Pe ┆ 6-0 ┆ 397 ┆ 6-0 ┆ li  │
│ 43- ┆ 632 ┆ c6d ┆ eli ┆ 781 ┆ 942 ┆ 087 ┆ 983 ┆     ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆ 999 ┆     ┆ 001 ┆     ┆     ┆ _pa ┆     ┆     ┆     ┆ rso ┆ 4-3 ┆ 83- ┆ 4-3 ┆     │
│ 154 ┆ 8   ┆ 9   ┆ ver ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆ nal ┆ 0T1 ┆ a4f ┆ 0T1 ┆     │
│ 0-4 ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 05: ┆ 05: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \_S ┆ 9:2 ┆ 6-4 ┆ 9:2 ┆     │
│ 781 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆ 10: ┆ 52: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aaS ┆ 3:3 ┆ 3d1 ┆ 3:3 ┆     │
│ -95 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \la ┆ 9+0 ┆ -af ┆ 9+0 ┆     │
│ 1e- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kel ┆ 0:0 ┆ 4c- ┆ 0:0 ┆     │
│ 6ab ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ogi ┆ 0   ┆ 628 ┆ 0   ┆     │
│ a32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c\e ┆     ┆ f9d ┆     ┆     │
│ 084 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ xam ┆     ┆ 0c0 ┆     ┆     │
│ 0d0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆ ee4 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s\c ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b\l ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ake ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se\ ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mar ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ket ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce\ ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bro ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nze ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \br ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ onz ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e_r ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ide ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ flo ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ w_t ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _co ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mpl ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ete ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆     ┆     │
│ 8ca ┆ R-7 ┆ D-8 ┆ eat ┆ 51. ┆ 0.0 ┆ 51. ┆ -0. ┆ LON ┆ 202 ┆ 202 ┆ 202 ┆ 21. ┆ 16  ┆ 15. ┆ 1.2 ┆ 4.5 ┆ cas ┆ 3.0 ┆ 5.0 ┆     ┆ C:\ ┆ 202 ┆ 19b ┆ 202 ┆ col │
│ 1fe ┆ d9d ┆ fb3 ┆ s_d ┆ 456 ┆ 228 ┆ 561 ┆ 076 ┆     ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 5   ┆     ┆ 25  ┆ 8   ┆ 5   ┆ h   ┆     ┆     ┆     ┆ _Pe ┆ 6-0 ┆ 397 ┆ 6-0 ┆ li  │
│ eb- ┆ 756 ┆ a9a ┆ eli ┆ 935 ┆ 78  ┆ 762 ┆ 129 ┆     ┆ 4-1 ┆ 4-1 ┆ 4-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rso ┆ 4-3 ┆ 83- ┆ 4-3 ┆     │
│ 8d3 ┆ 4   ┆ 3   ┆ ver ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nal ┆ 0T1 ┆ a4f ┆ 0T1 ┆     │
│ 1-4 ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 12: ┆ 12: ┆ 11: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \_S ┆ 9:2 ┆ 6-4 ┆ 9:2 ┆     │
│ e73 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15: ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ aaS ┆ 3:3 ┆ 3d1 ┆ 3:3 ┆     │
│ -89 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00  ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \la ┆ 9+0 ┆ -af ┆ 9+0 ┆     │
│ 7b- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kel ┆ 0:0 ┆ 4c- ┆ 0:0 ┆     │
│ 096 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ogi ┆ 0   ┆ 628 ┆ 0   ┆     │

📊 Fare stats:  min=£1.87  avg=£39.17  max=£142.58
🏙️ Cities: ['BER', 'LON', 'NYC', 'PAR', 'SYD', 'TYO', 'XYZ']

---
## Step 8 · Pipeline Audit Trail

Every pipeline run is logged with row counts, durations, quarantine ratios, and estimated costs.

In [16]:
log_path = LAKEHOUSE / registry.domain / "_logs"

column_list = [
    "run_id",
    "contract",
    "dataset",
    "status",
    "timestamp",
    "run_duration_seconds",
    "engine",
    "counts_source",
    "counts_total",
    "counts_good",
    "counts_quarantined",
    "quarantine_ratio",
    "estimated_cost",
    "cost_currency",
]
if log_path.exists():
    try:
        from deltalake import DeltaTable

        logs_df = pl.from_arrow(DeltaTable(str(log_path)).to_pyarrow_table())
        print(f"Run logs: {len(logs_df)} entries")
        display(logs_df.select("*").head(2))
    except ImportError:
        logs_df = pl.read_delta(str(log_path))
        print(f"Run logs: {len(logs_df)} entries")
        display(logs_df.select(column_list).head(10))
    except Exception as e:
        print(f"Run log read error: {e}")
else:
    print("No run log yet — this is expected for the first pipeline run.")

Run logs: 15 entries

shape: (2, 30)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pip ┆ run ┆ tim ┆ sta ┆ end ┆ run ┆ eng ┆ con ┆ sta ┆ dat ┆ dom ┆ sys ┆ env ┆ dat ┆ sta ┆ err ┆ sou ┆ cou ┆ cou ┆ cou ┆ cou ┆ qua ┆ est ┆ cos ┆ cos ┆ max ┆ max ┆ dlt ┆ slo ┆ rep │
│ eli ┆ _id ┆ est ┆ rt_ ┆ _ti ┆ _du ┆ ine ┆ tra ┆ ge  ┆ ase ┆ ain ┆ tem ┆ iro ┆ a_l ┆ tus ┆ or_ ┆ rce ┆ nts ┆ nts ┆ nts ┆ nts ┆ ran ┆ ima ┆ t_c ┆ t_c ┆ _so ┆ _wa ┆ _st ┆ _js ┆ ort │
│ ne_ ┆ --- ┆ amp ┆ tim ┆ me  ┆ rat ┆ --- ┆ ct  ┆ --- ┆ t   ┆ --- ┆ --- ┆ nme ┆ aye ┆ --- ┆ mes ┆ _pa ┆ _so ┆ _to ┆ _go ┆ _qu ┆ tin ┆ ted ┆ urr ┆ onf ┆ urc ┆ ter ┆ ate ┆ on  ┆ _js │
│ run ┆ str ┆ --- ┆ e   ┆ --- ┆ ion ┆ str ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ nt  ┆ r   ┆ str ┆ sag ┆ th  ┆ urc ┆ tal ┆ od  ┆ ara ┆ e_r ┆ _co ┆ enc ┆ ide ┆ e_m ┆ mar ┆ _js ┆ --- ┆ on  │
│ _id ┆     ┆ str ┆ --- ┆ str ┆ _se ┆     ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆     ┆ e   ┆ --- ┆ e   ┆ --- ┆ --- ┆ nti ┆ ati ┆ st  ┆ y   ┆ nce ┆ tim ┆ k_v ┆ on  ┆ str ┆ --- │
│ --- ┆     ┆     ┆ str ┆     ┆ con ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ --- ┆ str ┆ --- ┆ i64 ┆ i64 ┆ ned ┆ o   ┆ --- ┆ --- ┆ --- ┆ e   ┆ alu ┆ --- ┆     ┆ str │
│ str ┆     ┆     ┆     ┆     ┆ ds  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ str ┆ str ┆ --- ┆ e   ┆ str ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ c6b ┆ 27c ┆ 202 ┆ 202 ┆ 202 ┆ 0.0 ┆ duc ┆ Gol ┆ def ┆ gol ┆ mar ┆ rid ┆ loc ┆ gol ┆ suc ┆ nul ┆ C:\ ┆ 200 ┆ 200 ┆ 200 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ USD ┆ non ┆ 1.7 ┆ nul ┆ nul ┆ {"f ┆ {"r │
│ cb9 ┆ 25e ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 620 ┆ kdb ┆ d — ┆ aul ┆ d_r ┆ ket ┆ efl ┆ al  ┆ d   ┆ cee ┆ l   ┆ _Pe ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ 776 ┆ l   ┆ l   ┆ res ┆ un_ │
│ 9d- ┆ 97- ┆ 4-3 ┆ 4-3 ┆ 4-3 ┆ 66  ┆     ┆ Sur ┆ t   ┆ ide ┆ pla ┆ ow  ┆     ┆     ┆ ded ┆     ┆ rso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e9  ┆     ┆     ┆ hne ┆ id" │
│ a86 ┆ eca ┆ 0T1 ┆ 0T1 ┆ 0T1 ┆     ┆     ┆ ge  ┆     ┆ flo ┆ ce  ┆     ┆     ┆     ┆     ┆     ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ss" ┆ :   │
│ 9-4 ┆ b-4 ┆ 9:2 ┆ 9:2 ┆ 9:2 ┆     ┆     ┆ Pri ┆     ┆ w_s ┆     ┆     ┆     ┆     ┆     ┆     ┆ \_S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :   ┆ "27 │
│ 1c8 ┆ 6f4 ┆ 3:4 ┆ 3:4 ┆ 3:4 ┆     ┆     ┆ cin ┆     ┆ urg ┆     ┆     ┆     ┆     ┆     ┆     ┆ aaS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ {"s ┆ c25 │
│ -a3 ┆ -8a ┆ 2+0 ┆ 2.8 ┆ 2.9 ┆     ┆     ┆ g   ┆     ┆ e_p ┆     ┆     ┆     ┆     ┆     ┆     ┆ \la ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eco ┆ e97 │
│ b2- ┆ af- ┆ 0:0 ┆ 665 ┆ 292 ┆     ┆     ┆ ML  ┆     ┆ ric ┆     ┆     ┆     ┆     ┆     ┆     ┆ kel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nds ┆ -ec │
│ 690 ┆ f96 ┆ 0   ┆ 93+ ┆ 34+ ┆     ┆     ┆ Mod ┆     ┆ ing ┆     ┆     ┆     ┆     ┆     ┆     ┆ ogi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ ab- │
│ 98a ┆ f82 ┆     ┆ 00: ┆ 00: ┆     ┆     ┆ el  ┆     ┆ _mo ┆     ┆     ┆     ┆     ┆     ┆     ┆ c\e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ 46f │
│ 1ab ┆ 0b0 ┆     ┆ 00  ┆ 00  ┆     ┆     ┆ Log ┆     ┆ del ┆     ┆     ┆     ┆     ┆     ┆     ┆ xam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ 4-8 │
│ af0 ┆ 280 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "pa ┆ aaf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s\c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ss" ┆ -f9 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :   ┆ 6f8 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b\l ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ 20b │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ake ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ 028 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "th ┆ 0", │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se\ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆ "pi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hol ┆ pel │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ket ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_s ┆ ine │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eco ┆ _ru │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce\ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nds ┆ n_i │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sur ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ d": │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ge_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ "c6 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ inf ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ bcb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ere ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "so ┆ 99d │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nce ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ urc ┆ -a8 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _la ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e_s ┆ 69- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ndi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eco ┆ 41c │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ng  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nds ┆ 8-a │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ 3b2 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ -69 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ 098 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "so ┆ a1a │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ urc ┆ baf │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e_p ┆ 0", │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ass ┆ "en │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ gin │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ e": │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l}, ┆ "du │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "av ┆ ckd │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ail ┆ b", │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ abi ┆ "co │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lit ┆ ntr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y": ┆ act │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ {"r ┆ ":  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ati ┆ "Go │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o": ┆ ld  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ \u2 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ 014 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "pa ┆ Sur │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ss" ┆ ge  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :   ┆ Pri │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ cin │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ g   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "th ┆ ML  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆ Mod │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hol ┆ el  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d": ┆ Log │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ ",  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l}, ┆ "co │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "ro ┆ ntr │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ w_c ┆ act │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oun ┆ _fi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t": ┆ le_ │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ {"… ┆ n…  │
│ c6b ┆ 412 ┆ 202 ┆ 202 ┆ 202 ┆ 0.5 ┆ duc ┆ Gol ┆ def ┆ gol ┆ mar ┆ rid ┆ loc ┆ gol ┆ suc ┆ nul ┆ C:\ ┆ 171 ┆ 113 ┆ 113 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ USD ┆ non ┆ 1.7 ┆ nul ┆ nul ┆ {"f ┆ {"r │
│ cb9 ┆ 003 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆ 583 ┆ kdb ┆ d — ┆ aul ┆ d_r ┆ ket ┆ efl ┆ al  ┆ d   ┆ cee ┆ l   ┆ _Pe ┆ 8   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆ e   ┆ 776 ┆ l   ┆ l   ┆ res ┆ un_ │
│ 9d- ┆ cb- ┆ 4-3 ┆ 4-3 ┆ 4-3 ┆ 8   ┆     ┆ Dai ┆ t   ┆ ide ┆ pla ┆ ow  ┆     ┆     ┆ ded ┆     ┆ rso ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e9  ┆     ┆     ┆ hne ┆ id" │
│ a86 ┆ 38d ┆ 0T1 ┆ 0T1 ┆ 0T1 ┆     ┆     ┆ ly  ┆     ┆ flo ┆ ce  ┆     ┆     ┆     ┆     ┆     ┆ nal ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ss" ┆ :   │
│ 9-4 ┆ b-4 ┆ 9:2 ┆ 9:2 ┆ 9:2 ┆     ┆     ┆ Rid ┆     ┆ w_r ┆     ┆     ┆     ┆     ┆     ┆     ┆ \_S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :   ┆ "41 │
│ 1c8 ┆ 504 ┆ 3:4 ┆ 3:4 ┆ 3:4 ┆     ┆     ┆ er  ┆     ┆ ide ┆     ┆     ┆     ┆     ┆     ┆     ┆ aaS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ {"s ┆ 200 │
│ -a3 ┆ -a8 ┆ 2+0 ┆ 2.0 ┆ 2.6 ┆     ┆     ┆ Met ┆     ┆ r_d ┆     ┆     ┆     ┆     ┆     ┆     ┆ \la ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eco ┆ 3cb │
│ b2- ┆ 3c- ┆ 0:0 ┆ 765 ┆ 351 ┆     ┆     ┆ ric ┆     ┆ ail ┆     ┆     ┆     ┆     ┆     ┆     ┆ kel ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nds ┆ -38 │
│ 690 ┆ c00 ┆ 0   ┆ 73+ ┆ 83+ ┆     ┆     ┆ s   ┆     ┆ y_m ┆     ┆     ┆     ┆     ┆     ┆     ┆ ogi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ db- │
│ 98a ┆ ac7 ┆     ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆ etr ┆     ┆     ┆     ┆     ┆     ┆     ┆ c\e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ 450 │
│ 1ab ┆ 846 ┆     ┆ 00  ┆ 00  ┆     ┆     ┆     ┆     ┆ ics ┆     ┆     ┆     ┆     ┆     ┆     ┆ xam ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ 4-a │
│ af0 ┆ fa2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ple ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "pa ┆ 83c │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s\c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ss" ┆ -c0 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ola ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ :   ┆ 0ac │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ b\l ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ 784 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ake ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ 6fa │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "th ┆ 2", │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se\ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ res ┆ "pi │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mar ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hol ┆ pel │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ket ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d_s ┆ ine │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ pla ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eco ┆ _ru │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ce\ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nds ┆ n_i │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sil ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ d": │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ver ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ "c6 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ \si ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l,  ┆ bcb │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lve ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "so ┆ 99d │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r_r ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ urc ┆ -a8 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ide ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e_s ┆ 69- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ flo ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eco ┆ 41c │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ w_t ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nds ┆ 8-a │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ":  ┆ 3b2 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nul ┆ -69 │

---
## Step 8b · Quarantine View

In [17]:
table_name = "gold_rideflow_rider_lifetime_value"
quarantine_path = LAKEHOUSE / registry.domain / "_quarantine" / table_name

if quarantine_path.exists():
    try:
        from deltalake import DeltaTable

        quarantines_df = pl.from_arrow(DeltaTable(str(quarantine_path)).to_pyarrow_table())
        print(f"quarantine quarantines: {len(quarantines_df)} entries")
        display(quarantines_df.select("*").head(2))
    except ImportError:
        quarantines_df = pl.read_delta(str(quarantine_path))
        print(f"Run quarantines: {len(quarantines_df)} entries")
        display(quarantines_df.select(column_list).head(10))
    except Exception as e:
        print(f"Run quarantine read error: {e}")
else:
    print("No run quarantine yet — this is expected for the first pipeline run.")

No run quarantine yet — this is expected for the first pipeline run.

---
## Step 9 · 🚗 Launch Live Dashboard

The payoff! A real-time Panel dashboard that auto-refreshes from the Silver Delta tables every 3 seconds.

**5 Analytical Views:**
- 📈 Trip Volume Timeline (with Hour / Day / Week / Month aggregation)
- ⭐ Top 10 Drivers by Revenue (cross-table join with driver profiles)
- 🏙️ Revenue by City
- 👍 Driver Quality Distribution
- ⚡ Surge Multiplier Profile

> **Tip:** Use `dashboard.show()` to pop the dashboard out into a full browser tab for the best experience.

In [18]:
import importlib
import assets.dashboards.shared.streaming_dashboard

importlib.reload(assets.dashboards.shared.streaming_dashboard)

In [19]:
sys.path.insert(0, ".")
from assets.dashboards.shared.streaming_dashboard import create_streaming_dashboard_inline

dashboard = create_streaming_dashboard_inline(
    lakehouse_root=str(LAKEHOUSE),
    domain=registry.domain,
    system=registry.system,
    refresh_ms=3000,
)
dashboard

BokehModel(combine_events=True, render_bundle={'docs_json': {'899202a1-9ebe-464e-954e-0a5358d018b7': {'version…

---
## Step 10 · 🦆 Build Local DuckDB Catalog

Create a persistent `lakehouse_catalog.duckdb` file that maps all your Delta tables as SQL views.
Open this file in **DBeaver** (DuckDB driver) to browse and query your entire lakehouse with standard SQL.

```sql
-- Once opened in DBeaver, just run:
SELECT * FROM silver_trips WHERE city_code = 'LON' LIMIT 100;
```

In [20]:
import duckdb

catalog_path = str(LAKEHOUSE / f"lakehouse_catalog_{registry.domain}.duckdb")
con = duckdb.connect(catalog_path)

con.execute("INSTALL delta; LOAD delta;")

# Build views for every Delta table in the lakehouse
domain_root = LAKEHOUSE / registry.domain
for layer in ["bronze", "silver", "gold", "quarantine", "_logs"]:
    layer_path = domain_root / layer
    if not layer_path.exists():
        continue
    for table_dir in sorted(layer_path.iterdir()):
        if table_dir.is_dir() and not table_dir.name.startswith("_"):
            view_name = table_dir.name
            try:
                con.execute(f"CREATE OR REPLACE VIEW {view_name} AS SELECT * FROM delta_scan('{table_dir.as_posix()}')")
                row_count = con.execute(f"SELECT COUNT(*) FROM {view_name}").fetchone()[0]
                print(f"  ✅ {view_name}: {row_count:,} rows")
            except Exception as e:
                print(f"  ⚠️ {view_name}: {e}")

con.close()
print(f"\n🦆 Catalog saved → {catalog_path}")
print("   Open this file in DBeaver (DuckDB driver) to browse your lakehouse!")

  ✅ bronze_rideflow_driver_profiles: 148 rows
  ✅ bronze_rideflow_driver_telemetry: 7,916 rows
  ✅ bronze_rideflow_rider_app_events: 2,869 rows
  ✅ bronze_rideflow_rider_profiles: 391 rows
  ✅ bronze_rideflow_trip_cancellations: 179 rows
  ✅ bronze_rideflow_trip_completed: 1,838 rows
  ✅ bronze_rideflow_trip_requests: 1,453 rows
  ✅ silver_rideflow_driver_profiles: 148 rows
  ✅ silver_rideflow_driver_telemetry: 7,916 rows
  ✅ silver_rideflow_rider_profiles: 391 rows
  ✅ silver_rideflow_trips: 1,718 rows
  ✅ gold_rideflow_driver_scorecard: 822 rows
  ✅ gold_rideflow_rider_daily_metrics: 1,135 rows
  ✅ gold_rideflow_surge_pricing_model: 200 rows
  ✅ gold_rideflow_trip_kpis: 19 rows

🦆 Catalog saved → lakehouse\lakehouse_catalog_marketplace.duckdb
   Open this file in DBeaver (DuckDB driver) to browse your lakehouse!

---
## 🔄 Bonus: Incremental Streaming Mode

Re-run the simulator for the **next 7 hours** of synthetic data and trigger a full pipeline pass after each window.
This simulates what would happen in production with **Databricks Structured Streaming** — new micro-batches
land every hour, and the pipeline incrementally ingests them through Bronze → Silver → Gold.

| Parameter | Value |
| :-- | :-- |
| Simulation horizon | 7 hours from now |
| Window cadence | 60 min (1 window = 1 simulated hour) |
| Inter-window pause | 10 s (adjustable — set higher to watch dashboard animate) |
| Pipeline layers | Bronze → Silver → Gold (full pass each window) |

In [21]:
import time
from datetime import datetime, timedelta, timezone

if enable_incremental_streaming:
    # ── Configuration ─────────────────────────────────────────────────
    STREAM_HOURS = 7  # Simulate 7 hours into the future
    PAUSE_SECONDS = 10  # Pause between windows (increase to watch dashboard animate)
    MICRO_BATCHES = 10  # Files per entity per window

    stream_until = datetime.now(timezone.utc) + timedelta(hours=STREAM_HOURS)

    print("🔄 Incremental Streaming Mode")
    print(f"   Generating {STREAM_HOURS} hours of future data → up to {stream_until.strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"   Pause between windows: {PAUSE_SECONDS}s")
    print(f"   Pipeline engine: {engine}")
    print(f"{'=' * 70}")

    cumulative_rows = 0
    window_count = 0
    t_start = time.time()

    for window in sim.run(
        num_windows=STREAM_HOURS,
        include_seed=False,
        micro_batches=MICRO_BATCHES,
        up_to=stream_until,
        resume=True,
    ):
        window_count += 1
        cumulative_rows += window.total_rows

        print(
            f"\n⏱  Window {window_count}/{STREAM_HOURS} | "
            f"{window.timestamp.strftime('%Y-%m-%d %H:%M')} | "
            f"+{window.total_rows:,} rows  (cumulative: {cumulative_rows:,})"
        )

        # ── Re-ingest through the full pipeline ───────────────────────
        print("   🏗  Running pipeline (Bronze → Silver → Gold)...")
        runner = LakehousePipeline(registry, engine=engine)
        summary = runner.run(
            target_layers="bronze,silver,gold",
            retry_attempts=retry_attempts,
            retry_base_wait_seconds=retry_base_wait_seconds,
            parallel=parallel,
        )

        # Quick summary of what changed
        ingested = [r for r in summary.results if r.get("status") == "success"]
        skipped = [r for r in summary.results if r.get("status") in ("no_new_data", "no_new_rows")]
        print(f"   ✅ Pipeline pass complete: {len(ingested)} ingested, {len(skipped)} skipped")

        # ── Pause before next window ──────────────────────────────────
        if window_count < STREAM_HOURS:
            print(f"   ⏸  Pausing {PAUSE_SECONDS}s before next window...")
            time.sleep(PAUSE_SECONDS)

    elapsed = time.time() - t_start
    print(f"\n{'=' * 70}")
    print("✅ Incremental streaming complete!")
    print(f"   Windows processed: {window_count}")
    print(f"   Total rows generated: {cumulative_rows:,}")
    print(f"   Elapsed wall time: {elapsed / 60:.1f} min")
    print(f"   Dashboard should now reflect {STREAM_HOURS} additional hours of data.")
else:
    print("⏭  Incremental streaming disabled (set enable_incremental_streaming = True to activate)")

⏭  Incremental streaming disabled (set enable_incremental_streaming = True to activate)

---
## ✅ Data Products Published

This domain pipeline has successfully generated and published the following data products to the shared lakehouse:

| Data Product | Consumers |
| :-- | :-- |
| `silver_rideflow_trips` | Payments (reconciliation), Operations (support enrichment) |
| `silver_rideflow_driver_profiles` | Operations (background checks), Marketing (attribution) |
| `gold_rideflow_trip_kpis` | Executive Dashboard, Mesh Products |
| `gold_rideflow_rider_lifetime_value` | Marketing (LTV attribution), Finance (forecasting) |

Other domain pipelines (`08_rideflow_payments`, `09_rideflow_operations`, `10_rideflow_marketing`) read from these outputs — never from our internal Bronze tables. This enforces clean Data Mesh boundaries.

### Next Notebooks

- **`08_rideflow_payments.ipynb`** — Payments domain pipeline (Stripe charges, payouts, reconciliation)
- **`12_compliance_gdpr_rtbf.ipynb`** — Execute a Right-to-Be-Forgotten request across all domains
- **`14_data_mesh_dashboards.ipynb`** — Live observability across all domain pipelines