# Reading databases with LakeLogic

Every run here is **one contract file** in [`contracts/`](contracts/): where the data is, how to read it
(full, incremental or change data capture), the schema, the rules, and where good and bad rows go.
The notebook only seeds test data and calls `run_source()`.

| Contract | Source | Needs |
|---|---|---|
| `rides_sqlite.yaml` | SQLite file | nothing — runs anywhere |
| `rides_postgres.yaml` | PostgreSQL | `POSTGRES_URI` |
| `rides_azuresql.yaml` | Azure SQL / SQL Server, chunked | `AZURE_SQL_URI`, ODBC Driver 18 |
| `rides_azuresql_cdc.yaml` | SQL Server change data capture | `AZURE_SQL_URI`, CDC enabled (Azure SQL S3+) |
| `rides_mongodb.yaml` | MongoDB / Atlas / Cosmos DB (MongoDB API) / DocumentDB | `MONGO_URI` |

Connection strings (passwords included) are **environment variables**: a contract says `path: env:POSTGRES_URI`
and never holds a secret. A section whose variable is not set is skipped.

Each source holds the same data: 200 good rides, 10 with a negative fare, 5 with no city. Then 20 new rides
arrive and 5 are refunded. An incremental contract must read 215 rows, then only those 25, then nothing.

Needs `pip install "lakelogic[polars]" deltalake`, plus `psycopg2-binary` (Postgres), `pyodbc` (SQL Server),
`pymongo` (MongoDB). Local MongoDB: `docker run -d --name lakelogic-mongo-dev -p 27017:27017 mongo:7`.

In [1]:
import os
import shutil
import sys
from pathlib import Path

LAKELOGIC_SRC = None   # a local lakelogic checkout, if you are not using the released package
if LAKELOGIC_SRC:
    sys.path.insert(0, LAKELOGIC_SRC)
ENGINE = os.environ.get("ENGINE", "polars")   # polars | duckdb | spark
os.environ.setdefault("MONGO_URI", "mongodb://localhost:27017")

import polars as pl
from loguru import logger

from lakelogic import DataProcessor
from lakelogic.core.run_log import write_run_log
import seed   # test data only — LakeLogic reads through the contract

logger.remove()
pl.Config.set_tbl_rows(8)
pl.Config.set_tbl_width_chars(160)
shutil.rmtree("data", ignore_errors=True)   # a clean start: no run log, no bronze
Path("data").mkdir()


def as_polars(df):
    if isinstance(df, pl.DataFrame):
        return df
    return df.pl() if hasattr(df, "pl") else pl.from_pandas(df.toPandas())


def run(contract: str):
    """What a scheduled pipeline does with one contract: read, validate, write, log."""
    proc = DataProcessor(engine=ENGINE, contract=contract)
    good, bad = proc.run_source()[:2]
    proc.materialize(good, bad)
    write_run_log(proc.last_report, proc.contract, engine_name=ENGINE)  # remembers the watermark
    good, bad = as_polars(good), as_polars(bad)
    reasons = (bad["_lakelogic_errors"].explode().value_counts(sort=True)
               if bad.height and "_lakelogic_errors" in bad.columns else None)
    print(f"read {good.height + bad.height} rows: {good.height} good, {bad.height} quarantined")
    if reasons is not None:
        print(reasons)
    return good, bad


def show(contract: str):
    print(Path(contract).read_text())

## SQLite — incremental by `updated_at`

The contract:

In [2]:
show("contracts/rides_sqlite.yaml")

# Rides from a local SQLite file: runs anywhere, no server. The same contract shape works for
# Postgres, MySQL, SQL Server / Azure SQL; only source.path changes.
version: 1.0.0
dataset: rides
info: {title: bronze_rides_sqlite}
primary_key: [ride_id]
source:
  type: database
  path: sqlite:///data/rides.db       # a file relative to where the run starts
  load_mode: incremental              # each run reads only rows changed since the last one
  watermark_field: updated_at
model:
  fields:
    - {name: ride_id, type: long, required: true}
    - {name: city, type: string, required: true}
    - {name: fare, type: double, required: true}
    - {name: status, type: string}
    - {name: updated_at, type: timestamp}
quality:
  row_rules:
    - {name: fare_not_negative, sql: "fare >= 0"}
materialization:
  strategy: merge
  format: delta
  target_path: data/bronze/rides_sqlite
quarantine:
  target: data/quarantine/rides_sqlite
  format: delta
metadata:
  # The run log remembers the incremental watermark between runs.
  run_log_table: run_log
  run_log_backend: duckdb
  run_log_database: data/run_log_sqlite.duckdb   # one per contract: the watermark is per source

In [3]:
seed.seed("sqlite")
good, bad = run("contracts/rides_sqlite.yaml")      # first run: everything
good.head(3)

read 215 rows: 200 good, 15 quarantined
shape: (2, 2)
┌─────────────────────────────────┬───────┐
│ _lakelogic_errors               ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Rule failed: fare_not_negative… ┆ 10    │
│ Rule failed: city_required ("c… ┆ 5     │
└─────────────────────────────────┴───────┘

C:\Users\colli\AppData\Local\Temp\ipykernel_15324\3314527952.py:39: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  reasons = (bad["_lakelogic_errors"].explode().value_counts(sort=True)

shape: (3, 5)
┌─────────┬────────┬──────┬───────────┬─────────────────────┐
│ ride_id ┆ city   ┆ fare ┆ status    ┆ updated_at          │
│ ---     ┆ ---    ┆ ---  ┆ ---       ┆ ---                 │
│ i64     ┆ str    ┆ f64  ┆ str       ┆ datetime[μs]        │
╞═════════╪════════╪══════╪═══════════╪═════════════════════╡
│ 0       ┆ London ┆ 5.0  ┆ completed ┆ 2026-10-01 09:00:00 │
│ 1       ┆ Paris  ┆ 6.0  ┆ completed ┆ 2026-10-01 09:00:00 │
│ 2       ┆ Lagos  ┆ 7.0  ┆ completed ┆ 2026-10-01 09:00:00 │
└─────────┴────────┴──────┴───────────┴─────────────────────┘

In [4]:
seed.changes("sqlite")
good, bad = run("contracts/rides_sqlite.yaml")      # 20 new + 5 refunded
good.filter(pl.col("status") == "refunded")

read 25 rows: 25 good, 0 quarantined

shape: (5, 5)
┌─────────┬────────┬──────┬──────────┬─────────────────────┐
│ ride_id ┆ city   ┆ fare ┆ status   ┆ updated_at          │
│ ---     ┆ ---    ┆ ---  ┆ ---      ┆ ---                 │
│ i64     ┆ str    ┆ f64  ┆ str      ┆ datetime[μs]        │
╞═════════╪════════╪══════╪══════════╪═════════════════════╡
│ 0       ┆ London ┆ 5.0  ┆ refunded ┆ 2026-10-01 10:01:00 │
│ 1       ┆ Paris  ┆ 6.0  ┆ refunded ┆ 2026-10-01 10:01:00 │
│ 2       ┆ Lagos  ┆ 7.0  ┆ refunded ┆ 2026-10-01 10:01:00 │
│ 3       ┆ London ┆ 8.0  ┆ refunded ┆ 2026-10-01 10:01:00 │
│ 4       ┆ Paris  ┆ 9.0  ┆ refunded ┆ 2026-10-01 10:01:00 │
└─────────┴────────┴──────┴──────────┴─────────────────────┘

In [5]:
run("contracts/rides_sqlite.yaml");                 # nothing changed: nothing read

read 0 rows: 0 good, 0 quarantined

## PostgreSQL

Set `POSTGRES_URI`, e.g. `postgresql://user:password@host:5432/lakelogic_test?sslmode=require`.

In [6]:
show("contracts/rides_postgres.yaml")

# Rides from PostgreSQL (here Azure Database for PostgreSQL). The connection string, password
# included, is an environment variable: the contract names it, never holds it.
version: 1.0.0
dataset: rides
info: {title: bronze_rides_postgres}
primary_key: [ride_id]
source:
  type: database
  path: env:POSTGRES_URI                # postgresql://user:password@host:5432/db?sslmode=require â€” kept out of the contract
  load_mode: incremental              # each run reads only rows changed since the last one
  watermark_field: updated_at
model:
  fields:
    - {name: ride_id, type: long, required: true}
    - {name: city, type: string, required: true}
    - {name: fare, type: double, required: true}
    - {name: status, type: string}
    - {name: updated_at, type: timestamp}
quality:
  row_rules:
    - {name: fare_not_negative, sql: "fare >= 0"}
materialization:
  strategy: merge
  format: delta
  target_path: data/bronze/rides_postgres
quarantine:
  target: data/quarantine/rides_postgres
  format: delta
metadata:
  # The run log remembers the incremental watermark between runs.
  run_log_table: run_log
  run_log_backend: duckdb
  run_log_database: data/run_log_postgres.duckdb   # one per contract: the watermark is per source

In [7]:
if os.environ.get("POSTGRES_URI"):
    seed.seed("postgres")
    run("contracts/rides_postgres.yaml")
    seed.changes("postgres")
    run("contracts/rides_postgres.yaml")
    run("contracts/rides_postgres.yaml")
else:
    print("POSTGRES_URI not set — skipped")

C:\Users\colli\AppData\Local\Temp\ipykernel_15324\3314527952.py:39: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  reasons = (bad["_lakelogic_errors"].explode().value_counts(sort=True)

read 215 rows: 200 good, 15 quarantined
shape: (2, 2)
┌─────────────────────────────────┬───────┐
│ _lakelogic_errors               ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Rule failed: fare_not_negative… ┆ 10    │
│ Rule failed: city_required ("c… ┆ 5     │
└─────────────────────────────────┴───────┘

read 25 rows: 25 good, 0 quarantined

read 0 rows: 0 good, 0 quarantined

## Azure SQL / SQL Server — chunked reads

Set `AZURE_SQL_URI`, e.g. `mssql://user:password@server.database.windows.net:1433/lakelogic_test?encrypt=true`.
`fetch_size` reads the table in chunks.

In [8]:
show("contracts/rides_azuresql.yaml")

# Rides from Azure SQL / SQL Server. Rows are fetched in chunks of fetch_size, so a large
# table never has to fit in memory at once.
version: 1.0.0
dataset: rides
info: {title: bronze_rides_azuresql}
primary_key: [ride_id]
source:
  type: database
  path: env:AZURE_SQL_URI               # mssql://user:password@server.database.windows.net:1433/db?encrypt=true
  load_mode: incremental              # each run reads only rows changed since the last one
  watermark_field: updated_at
  options:
    fetch_size: 1000                  # read in chunks
model:
  fields:
    - {name: ride_id, type: long, required: true}
    - {name: city, type: string, required: true}
    - {name: fare, type: double, required: true}
    - {name: status, type: string}
    - {name: updated_at, type: timestamp}
quality:
  row_rules:
    - {name: fare_not_negative, sql: "fare >= 0"}
materialization:
  strategy: merge
  format: delta
  target_path: data/bronze/rides_azuresql
quarantine:
  target: data/quarantine/rides_azuresql
  format: delta
metadata:
  # The run log remembers the incremental watermark between runs.
  run_log_table: run_log
  run_log_backend: duckdb
  run_log_database: data/run_log_azuresql.duckdb   # one per contract: the watermark is per source

In [9]:
if os.environ.get("AZURE_SQL_URI"):
    seed.seed("azuresql")
    run("contracts/rides_azuresql.yaml")
    seed.changes("azuresql")
    run("contracts/rides_azuresql.yaml")
    run("contracts/rides_azuresql.yaml")
else:
    print("AZURE_SQL_URI not set — skipped")

C:\Users\colli\AppData\Local\Temp\ipykernel_15324\3314527952.py:39: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  reasons = (bad["_lakelogic_errors"].explode().value_counts(sort=True)

read 215 rows: 200 good, 15 quarantined
shape: (2, 2)
┌─────────────────────────────────┬───────┐
│ _lakelogic_errors               ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Rule failed: fare_not_negative… ┆ 10    │
│ Rule failed: city_required ("c… ┆ 5     │
└─────────────────────────────────┴───────┘

read 25 rows: 25 good, 0 quarantined

read 0 rows: 0 good, 0 quarantined

## SQL Server change data capture

CDC reads the database's own change log, so it sees **deletes** too, and needs no `updated_at` column.
Each row carries `_lakelogic_cdc_op` (insert / update / delete). Azure SQL needs the S3 tier or higher,
so this section only runs when `RUN_CDC=1`: enable CDC on `rides` first (see the contract's header).

In [10]:
show("contracts/rides_azuresql_cdc.yaml")

# Rides from SQL Server / Azure SQL change data capture: inserts, updates AND deletes, read from
# the database's own change log. Each run reads the changes committed since the last run.
# Needs CDC enabled on the database and table (Azure SQL: S3 tier or higher):
#   EXEC sys.sp_cdc_enable_db;
#   EXEC sys.sp_cdc_enable_table @source_schema='dbo', @source_name='rides', @role_name=NULL;
version: 1.0.0
dataset: rides
info: {title: bronze_rides_azuresql_cdc}
primary_key: [ride_id]
source:
  type: database
  path: env:AZURE_SQL_URI
  load_mode: cdc
  options:
    cdc_provider: azuresql
    cdc_capture_instance: dbo_rides   # the capture instance sp_cdc_enable_table created
  # Each row carries _lakelogic_cdc_op (insert / update / delete) and _lakelogic_cdc_ts (commit time).
model:
  fields:
    - {name: ride_id, type: long, required: true}
    - {name: city, type: string}
    - {name: fare, type: double}
    - {name: status, type: string}
    - {name: updated_at, type: timestamp}
quality:
  row_rules:
    - {name: fare_not_negative, sql: "fare IS NULL OR fare >= 0"}
materialization:
  strategy: merge
  format: delta
  target_path: data/bronze/rides_azuresql_cdc
metadata:
  run_log_table: run_log
  run_log_backend: duckdb
  run_log_database: data/run_log_azuresql_cdc.duckdb   # one per contract: the watermark is per source

In [11]:
if os.environ.get("AZURE_SQL_URI") and os.environ.get("RUN_CDC") == "1":
    good, bad = run("contracts/rides_azuresql_cdc.yaml")
    print(good["_lakelogic_cdc_op"].value_counts())
else:
    print("RUN_CDC=1 and AZURE_SQL_URI needed — skipped")

RUN_CDC=1 and AZURE_SQL_URI needed — skipped

## MongoDB (also Atlas, Cosmos DB's MongoDB API, DocumentDB)

`dataset` is the collection. Nested `customer.name` becomes `customer_name`; the `items` array stays JSON text.
`options.filter` is a MongoDB query the server applies. One document has `fare: "abc"` and one has no
customer — both are quarantined, with the reason.

In [12]:
show("contracts/rides_mongodb.yaml")

# Rides from a MongoDB-protocol collection: MongoDB, Atlas, Azure Cosmos DB (MongoDB API) or
# Amazon DocumentDB. dataset is the collection. Nested objects are flattened into columns
# (customer.name -> customer_name); arrays stay as JSON text for explode / json_extract.
version: 1.0.0
dataset: rides
info: {title: bronze_rides_mongodb}
primary_key: [ride_id]
source:
  type: database
  path: env:MONGO_URI                 # mongodb://host:27017 or mongodb+srv://user:password@cluster/...
  flatten_nested: true
  load_mode: incremental
  watermark_field: updated_at
  options:
    database: lakelogic_test
    filter: {status: {$ne: test}}     # a MongoDB query, applied by the server
model:
  fields:
    - {name: _id, type: string, required: true}
    - {name: ride_id, type: long, required: true}
    - {name: customer_name, type: string, required: true}
    - {name: fare, type: double, required: true}
    - {name: status, type: string}
    - {name: updated_at, type: timestamp}
quality:
  row_rules:
    - {name: fare_not_negative, sql: "fare >= 0"}
materialization:
  strategy: merge
  format: delta
  target_path: data/bronze/rides_mongodb
quarantine:
  target: data/quarantine/rides_mongodb
  format: delta
metadata:
  run_log_table: run_log
  run_log_backend: duckdb
  run_log_database: data/run_log_mongodb.duckdb   # one per contract: the watermark is per source

In [13]:
try:
    seed.seed("mongodb")
except Exception as exc:
    print(f"MongoDB not reachable at {os.environ['MONGO_URI']} — skipped ({type(exc).__name__})")
else:
    good, bad = run("contracts/rides_mongodb.yaml")
    display(good.select("ride_id", "customer_name", "customer_tier", "fare", "items").head(3))
    seed.changes("mongodb")
    run("contracts/rides_mongodb.yaml")
    run("contracts/rides_mongodb.yaml")

read 216 rows: 204 good, 12 quarantined
shape: (4, 2)
┌─────────────────────────────────┬───────┐
│ _lakelogic_errors               ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Rule failed: fare_not_negative… ┆ 11    │
│ Rule failed: customer_name_req… ┆ 1     │
│ Type Mismatch: fare cannot be … ┆ 1     │
│ Rule failed: fare_required ("f… ┆ 1     │
└─────────────────────────────────┴───────┘

C:\Users\colli\AppData\Local\Temp\ipykernel_15324\3314527952.py:39: DeprecationWarning: In Polars 2.0, the default behavior for `empty_as_null` will change to `False`. To keep the current behavior, explicitly set `empty_as_null=True`.
  reasons = (bad["_lakelogic_errors"].explode().value_counts(sort=True)

shape: (3, 5)
┌─────────┬───────────────┬───────────────┬──────┬──────────────────────────┐
│ ride_id ┆ customer_name ┆ customer_tier ┆ fare ┆ items                    │
│ ---     ┆ ---           ┆ ---           ┆ ---  ┆ ---                      │
│ i64     ┆ str           ┆ str           ┆ f64  ┆ str                      │
╞═════════╪═══════════════╪═══════════════╪══════╪══════════════════════════╡
│ 0       ┆ rider0        ┆ gold          ┆ 5.0  ┆ [{"sku": "A", "qty": 1}] │
│ 1       ┆ rider1        ┆ gold          ┆ 6.0  ┆ [{"sku": "A", "qty": 1}] │
│ 2       ┆ rider2        ┆ gold          ┆ 7.0  ┆ [{"sku": "A", "qty": 1}] │
└─────────┴───────────────┴───────────────┴──────┴──────────────────────────┘

read 25 rows: 25 good, 0 quarantined

read 0 rows: 0 good, 0 quarantined